model dsmodelIterationSelect
  extends NHES.Desalination.MEE.Examples.RankineMEE;
  annotation(__Dymola_SimulationIterationVariables={"mEE_PF8_FC.effect7.Evaporator.Xo[2]",
   "mEE_PF8_FC.effect7.Evaporator.T", "mEE_PF8_FC.effect7.Evaporator.alphag", 
  "mEE_PF8_FC.effect7.Evaporator.Vm", "mEE_PF8_FC.effect7.Brine_Inlet_Port.p", 
  "mEE_PF8_FC.temperature7.port.h_outflow_inStream", "mEE_PF8_FC.CV7.dp", 
  "mEE_PF8_FC.sensorBus.p7", "mEE_PF8_FC.BrineFCV7.PID.limiter.u", 
  "mEE_PF8_FC.effect8.Evaporator.Xo[2]", "mEE_PF8_FC.effect8.Evaporator.T", 
  "mEE_PF8_FC.effect8.Brine_Inlet_Port.p", "mEE_PF8_FC.effect8.Evaporator.alphag",
   "mEE_PF8_FC.effect8.Evaporator.Vm", "mEE_PF8_FC.effect4.Evaporator.Xo[2]", 
  "mEE_PF8_FC.effect4.Evaporator.T", "mEE_PF8_FC.effect4.Brine_Inlet_Port.p", 
  "mEE_PF8_FC.effect4.Evaporator.alphag", "mEE_PF8_FC.effect4.Evaporator.Vm", 
  "mEE_PF8_FC.effect2.Evaporator.Xo[2]", "mEE_PF8_FC.effect2.Evaporator.alphag",
   "mEE_PF8_FC.effect2.Evaporator.Vm", "mEE_PF8_FC.effect2.Evaporator.T", 
  "mEE_PF8_FC.effect2.Brine_Inlet_Port.p", "mEE_PF8_FC.temperature2.port.h_outflow_inStream",
   "mEE_PF8_FC.CV2.dp", "mEE_PF8_FC.sensorBus.p2", "mEE_PF8_FC.effect3.Evaporator.Xo[2]",
   "mEE_PF8_FC.effect3.Evaporator.T", "mEE_PF8_FC.effect3.Brine_Inlet_Port.p", 
  "mEE_PF8_FC.effect3.Evaporator.alphag", "mEE_PF8_FC.effect3.Evaporator.Vm", 
  "mEE_PF8_FC.effect1.Evaporator.Xo[2]", "mEE_PF8_FC.effect1.Evaporator.alphag",
   "mEE_PF8_FC.effect1.Evaporator.Vm", "mEE_PF8_FC.effect1.Evaporator.T", 
  "mEE_PF8_FC.effect1.Brine_Inlet_Port.p", "mEE_PF8_FC.BrineFCV1.PID.limiter.u",
   "mEE_PF8_FC.BrineFCV2.PID.limiter.u", "mEE_PF8_FC.BrineFCV3.PID.limiter.u", 
  "mEE_PF8_FC.BrineFCV4.PID.limiter.u", "mEE_PF8_FC.effect6.Evaporator.Xo[2]", 
  "mEE_PF8_FC.effect6.Evaporator.alphag", "mEE_PF8_FC.effect6.Evaporator.Vm", 
  "mEE_PF8_FC.effect6.Evaporator.T", "mEE_PF8_FC.effect6.Brine_Inlet_Port.p", 
  "mEE_PF8_FC.BrineFCV6.PID.limiter.u", "mEE_PF8_FC.BrineFCV8.PID.limiter.u", 
  "mEE_PF8_FC.effect5.Evaporator.Xo[2]", "mEE_PF8_FC.effect5.Evaporator.alphag",
   "mEE_PF8_FC.effect5.Evaporator.Vm", "mEE_PF8_FC.effect5.Evaporator.T", 
  "mEE_PF8_FC.effect5.Brine_Inlet_Port.p", "mEE_PF8_FC.FCV5.PID.limiter.u", 
  "mEE_PF8_FC.temperature1.port.h_outflow_inStream", "mEE_PF8_FC.CV1.dp", 
  "mEE_PF8_FC.sensorBus.p1", "mEE_PF8_FC.temperature3.port.h_outflow_inStream", 
  "mEE_PF8_FC.CV3.dp", "mEE_PF8_FC.sensorBus.p3", "mEE_PF8_FC.temperature4.port.h_outflow_inStream",
   "mEE_PF8_FC.CV4.dp", "mEE_PF8_FC.sensorBus.p4", "mEE_PF8_FC.temperature5.port.h_outflow_inStream",
   "mEE_PF8_FC.CV5.dp", "mEE_PF8_FC.sensorBus.p5", "mEE_PF8_FC.temperature6.port.h_outflow_inStream",
   "mEE_PF8_FC.CV6.dp", "mEE_PF8_FC.sensorBus.p6", "mEE_PF8_FC.temperature8.port.h_outflow_inStream",
   "mEE_PF8_FC.sensorBus.p8", "der(mEE_PF8_FC.preHeater.preheaterTube.Heat_Port.T)"});
end dsmodelIterationSelect;
