model dsmodelIterationSelect
  extends NHES.Systems.IndustrialProcess.HighTempSteamElectrolysis.Examples.HTSE_TightlyCoupled_SteamFlowCtrl_Test_FY17;
  annotation(__Dymola_SimulationIterationVariables={"IP.compressionSystem.junction.T",
   "IP.FCV_anSOEC.port_a.p", "IP.compressionSystem.junction.fluid.X[1]", 
  "IP.compressionSystem.junction.fluid.X[2]", "IP.HTSEvessel.controlledSOEC.SOECstack.yanodeOut[2]",
   "IP.HTSEvessel.anodeIn.p", "IP.compressionSystem.junction.U", 
  "IP.compressionSystem.junction.M", "IP.HTSEvessel.toppingHeater_anodeGas.heatedPipe.cp_mean",
   "IP.HTSEvessel.toppingHeater_anodeGas.heatedPipe.M", "IP.HTSEvessel.toppingHeater_anodeGas.heatedPipe.rho_mean",
   "IP.HTSEvessel.toppingHeater_anodeGas.heatedPipe.T_mean", "IP.HTSEvessel.controlledSOEC.SOECstack.cpA",
   "IP.HTSEvessel.controlledSOEC.SOECstack.N_O2_anode", "IP.HTSEvessel.controlledSOEC.SOECstack.N_N2_anode",
   "IP.HTSEvessel.controlledSOEC.SOECstack.rho_AnodeAvg", "IP.HTSEvessel.controlledSOEC.SOECstack.TAavg",
   "IP.actuator_wAnode_in.y", "IP.compressionSystem.comp_1st.state_gas_out.p", 
  "IP.compressionSystem.comp_2nd.Ti", "IP.compressionSystem.comp_2nd.state_gas_out.p",
   "IP.compressionSystem.comp_3rd.Ti", "IP.FCV_anSOEC.port_b.h_outflow", 
  "IP.HTSEvessel.hEX_anodeGasRecup_ROM.tube_out.h_outflow", "IP.HTSEvessel.toppingHeater_anodeGas.port_b.h_outflow",
   "IP.HTSEvessel.controlledSOEC.SOECstack.anodeFlangeOut.h_outflow", 
  "IP.PCV_anSOEC.dp", "IP.turbine.Tf", "IP.FCV_catSOEC.dp", "IP.HTSEvessel.controlledSOEC.SOECstack.XcathodeIn[1]",
   "IP.HTSEvessel.controlledSOEC.SOECstack.XcathodeIn[2]", "IP.HTSEvessel.controlledSOEC.SOECstack.ycathodeOut[1]",
   "IP.idealRecycle_H2.actuator_wH2_in.y", "IP.feedPump.pump.U", 
  "IP.feedPump.pump.m", "IP.HTSEvessel.toppingHeater_cathodeGas.heatedPipe.cp_mean",
   "IP.HTSEvessel.toppingHeater_cathodeGas.heatedPipe.M", "IP.HTSEvessel.toppingHeater_cathodeGas.heatedPipe.rho_mean",
   "IP.HTSEvessel.toppingHeater_cathodeGas.heatedPipe.T_mean", "IP.HTSEvessel.controlledSOEC.SOECstack.cpC",
   "IP.HTSEvessel.controlledSOEC.SOECstack.N_H2O_cathode", "IP.HTSEvessel.controlledSOEC.SOECstack.N_H2_cathode",
   "IP.HTSEvessel.controlledSOEC.SOECstack.rho_CathodeAvg", "IP.HTSEvessel.controlledSOEC.SOECstack.TCavg",
   "IP.actuator_wCathode_in.y", "IP.feedPump.pump.medium.p", "IP.feedPump.pump.medium.h",
   "IP.feedPump.pump.s", "IP.hEX_nuclearHeatCathodeGasRecup_ROM.tube_in.h_outflow",
   "IP.HTSEvessel.hEX_cathodeGasRecup_ROM.tube_out.h_outflow", "IP.HTSEvessel.toppingHeater_cathodeGas.port_b.h_outflow",
   "IP.HTSEvessel.controlledSOEC.SOECstack.lossActOPanode", "IP.HTSEvessel.controlledSOEC.SOECstack.lossActOPcathode",
   "IP.PCV_catSOEC.dp", "IP.HTSEvessel.cathodeIn.h_outflow", "der(IP.HTSEvessel.controlledSOEC.SOECstack.TCavg)",
   "der(IP.HTSEvessel.controlledSOEC.SOECstack.XcathodeAvg[1])", 
  "der(IP.HTSEvessel.controlledSOEC.SOECstack.XcathodeIn[1])", "der(IP.HTSEvessel.toppingHeater_cathodeGas.heatedPipe.T_mean)",
   "der(IP.FCV_catSOEC.dp)", "der(IP.actuator_wCathode_in.y)", "der(IP.HTSEvessel.controlledSOEC.SOECstack.XcathodeAvg[2])",
   "der(IP.HTSEvessel.controlledSOEC.SOECstack.XcathodeIn[2])", "der(IP.HTSEvessel.controlledSOEC.SOECstack.ycathodeOut[1])",
   "IP.HTSEvessel.cathodeOut.h_outflow", "IP.TCV_anodeGas.dp", "IP.TCV_cathodeGas.dp",
   "IP.hEX_nuclearHeatCathodeGasRecup_ROM.shell_out.h_outflow", "IP.nFlow_out.port_a.h_outflow",
   "IP.TCV_anodeGas.port_a.h_outflow", "IP.hEX_nuclearHeatAnodeGasRecup_ROM.shell_out.h_outflow",
   "IP.mH2O_in.port_a.h_outflow", "der(IP.compressionSystem.flowSplit.medium.h)",
   "IP.compressionSystem.ISC_1st.shell_out.h_outflow", "IP.compressionSystem.ISC_2nd.shell_out.h_outflow",
   "der(IP.compressionSystem.flowJoin.medium.h)", "IP.cascadeCtrl_yH2.mixer_H2Recycled.T"});
end dsmodelIterationSelect;
