model dsmodelIterationSelect
  extends NHES.Systems.IndustrialProcess.ReverseOsmosisDesalination.Examples.RO_Desal_NHES_Test;
  annotation(__Dymola_SimulationIterationVariables={"IP.rO_unit.VesselsStage1.stateRetentate.T",
   "IP.rO_unit.VesselsStage1.stateFeed.T", "IP.rO_unit.VesselsStage1.FeedFlange.m_flow",
   "IP.rO_unit.VesselsStage1.RetentateFlange.m_flow", "IP.rO_unit.VesselsStage2.stateRetentate.p",
   "IP.rO_unit.VesselsStage2.stateRetentate.T", "IP.rO_unit.VesselsStage2.Sr", 
  "IP.rO_unit.VesselsStage1.Sr", "IP.rO_unit.VesselsStage2.stateFeed.T", 
  "IP.rO_unit.VesselsStage1.stateRetentate.p", "IP.pumpingSystem.feedPump.s", 
  "IP.pumpingSystem.feedPump.medium.T", "IP.rO_unit.VesselsStage1.stateFeed.p", 
  "IP.rO_unit.VesselsStage1.stateFeed.X[2]", "IP.rO_unit.VesselsStage2.Osmotic_P_Pa",
   "IP.rO_unit.VesselsStage2.Sp", "IP.rO_unit.VesselsStage1.Osmotic_P_Pa", 
  "IP.rO_unit.VesselsStage1.Sp", "IP.rO_unit.flowJoin.medium.T"});
end dsmodelIterationSelect;
