model dsmodelIterationSelect
  extends NHES.Systems.BalanceOfPlant.StagebyStageTurbineSecondary.Examples.Eight_Stage_Turbine;
  annotation(__Dymola_SimulationIterationVariables={"der(Stator8.states[1].h)", 
  "der(MoistSep3.separator.medium.h)", "der(MoistSep3.separator.medium.p)", 
  "Stator8.v_z[1]", "der(Stator7.states[1].h)", "der(MoistSep2.separator.medium.h)",
   "der(MoistSep2.separator.medium.p)", "Stator7.v_z[1]", "turbine_Tap2.Tap_flow.m_flow",
   "Stator6.v_z[1]", "der(Stator5.states[1].h)", "der(MoistSep1.separator.medium.h)",
   "der(MoistSep1.separator.medium.p)", "Stator5.v_z[1]", "turbine_Tap1.Tap_flow.m_flow",
   "Stator4.v_z[1]", "turbine_Tap.Tap_flow.m_flow", "Stator3.v_z[1]", 
  "Stator2.v_z[1]", "Stator1.v_z[1]", "Rotor1.v_z[1]", "Rotor2.v_z[1]", 
  "Rotor3.v_z[1]", "Rotor4.v_z[1]", "Rotor5.v_z[1]", "Rotor6.v_z[1]", 
  "Rotor7.v_z[1]", "Rotor8.v_z[1]", "Rotor8.vnet[1]", "Rotor8.vnet[2]", 
  "Rotor8.vnet[3]", "Stator8.vnet[1]", "Stator8.vnet[2]", "Rotor7.vnet[1]", 
  "Rotor7.vnet[2]", "Rotor7.vnet[3]", "Stator7.vnet[1]", "Stator7.vnet[2]", 
  "Rotor6.vnet[1]", "Rotor6.vnet[2]", "Rotor6.vnet[3]", "Stator6.vnet[1]", 
  "Stator6.vnet[2]", "Stator5.vnet[1]", "Stator5.vnet[2]", "Rotor5.vnet[1]", 
  "Rotor5.vnet[2]", "Rotor5.vnet[3]", "Rotor4.vnet[1]", "Rotor4.vnet[2]", 
  "Rotor4.vnet[3]", "Stator4.vnet[1]", "Stator4.vnet[2]", "Rotor3.vnet[1]", 
  "Rotor3.vnet[2]", "Rotor3.vnet[3]", "Stator3.vnet[1]", "Stator3.vnet[2]", 
  "Rotor2.vnet[1]", "Rotor2.vnet[2]", "Rotor2.vnet[3]", "Stator2.vnet[1]", 
  "Stator2.vnet[2]", "Rotor1.vnet[1]", "Rotor1.vnet[2]", "Rotor1.vnet[3]", 
  "Stator1.vnet[1]", "Stator1.vnet[2]"});
end dsmodelIterationSelect;
