model dsmodelIterationSelect
  extends NHES.Systems.Examples.SMR_Coupling_4_loop_control;
  annotation(__Dymola_SimulationIterationVariables={"der(nuScale_Tave_enthalpy.Upper_Riser.mediums[1].h)",
   "der(nuScale_Tave_enthalpy.Lower_Riser.mediums[2].p)", "der(nuScale_Tave_enthalpy.Lower_Riser.mediums[2].h)",
   "der(nuScale_Tave_enthalpy.PressurizerandTopper.mediums[1].h)", 
  "der(nuScale_Tave_enthalpy.Upper_Riser.mediums[2].p)", "der(nuScale_Tave_enthalpy.Upper_Riser.mediums[2].h)",
   "nuScale_Tave_enthalpy.pipeLoss.port_a.m_flow", "der(nuScale_Tave_enthalpy.pressurizer_tee.medium.h)",
   "der(nuScale_Tave_enthalpy.pressurizer_tee.medium.p)", "der(nuScale_Tave_enthalpy.PressurizerandTopper.mediums[2].h)",
   "der(nuScale_Tave_enthalpy.DownComer.mediums[1].h)", "der(nuScale_Tave_enthalpy.DownComer.mediums[1].p)",
   "der(nuScale_Tave_enthalpy.STHX.shell.mediums[10].h)", "BOP.steamTurbine.portHP.p",
   "EM.port_b2.p"});
end dsmodelIterationSelect;
