model dsmodelIterationSelect
  extends NHES.Systems.PrimaryHeatSystem.HTGR.HTGR_Rankine.Examples.Rankine_HTGR_OneStageTurbine_Transient;
  annotation(__Dymola_SimulationIterationVariables={"BOP.port_b.p", 
  "feedWaterpump.head", "BOP.steamTurbine.portHP.p", "hTGR_PebbleBed_Primary_Loop.core.coolantSubchannel.Ts_wall[7, 1]",
   "hTGR_PebbleBed_Primary_Loop.core.coolantSubchannel.Ts_wall[6, 1]", 
  "hTGR_PebbleBed_Primary_Loop.core.coolantSubchannel.Ts_wall[5, 1]", 
  "hTGR_PebbleBed_Primary_Loop.core.coolantSubchannel.Ts_wall[4, 1]", 
  "hTGR_PebbleBed_Primary_Loop.core.coolantSubchannel.Ts_wall[3, 1]", 
  "hTGR_PebbleBed_Primary_Loop.core.coolantSubchannel.Ts_wall[8, 1]", 
  "hTGR_PebbleBed_Primary_Loop.core.coolantSubchannel.Ts_wall[2, 1]", 
  "hTGR_PebbleBed_Primary_Loop.core.coolantSubchannel.flowModel.dps_fg[1]", 
  "hTGR_PebbleBed_Primary_Loop.compressor_Controlled.Ti", "hTGR_PebbleBed_Primary_Loop.compressor_Controlled.gas_iso.T",
   "hTGR_PebbleBed_Primary_Loop.boundary1.T_in_internal", "hTGR_PebbleBed_Primary_Loop.core.port_a.p",
   "hTGR_PebbleBed_Primary_Loop.core.coolantSubchannel.state_a.T", 
  "hTGR_PebbleBed_Primary_Loop.core.coolantSubchannel.state_a.p", 
  "hTGR_PebbleBed_Primary_Loop.core.coolantSubchannel.Ts_wall[1, 1]", 
  "hTGR_PebbleBed_Primary_Loop.core.fuelModel[1].Fuel_kernel.port_b1.T", 
  "hTGR_PebbleBed_Primary_Loop.core.fuelModel[1].Fuel_kernel_center.port_b1.T", 
  "hTGR_PebbleBed_Primary_Loop.core.fuelModel[2].Fuel_kernel.port_b1.T", 
  "hTGR_PebbleBed_Primary_Loop.core.fuelModel[2].Fuel_kernel_center.port_b1.T", 
  "hTGR_PebbleBed_Primary_Loop.core.fuelModel[3].Fuel_kernel.port_b1.T", 
  "hTGR_PebbleBed_Primary_Loop.core.fuelModel[3].Fuel_kernel_center.port_b1.T", 
  "hTGR_PebbleBed_Primary_Loop.core.fuelModel[4].Fuel_kernel.port_b1.T", 
  "hTGR_PebbleBed_Primary_Loop.core.fuelModel[4].Fuel_kernel_center.port_b1.T", 
  "hTGR_PebbleBed_Primary_Loop.core.fuelModel[5].Fuel_kernel.port_b1.T", 
  "hTGR_PebbleBed_Primary_Loop.core.fuelModel[5].Fuel_kernel_center.port_b1.T", 
  "hTGR_PebbleBed_Primary_Loop.core.fuelModel[6].Fuel_kernel.port_b1.T", 
  "hTGR_PebbleBed_Primary_Loop.core.fuelModel[6].Fuel_kernel_center.port_b1.T", 
  "hTGR_PebbleBed_Primary_Loop.core.fuelModel[7].Fuel_kernel.port_b1.T", 
  "hTGR_PebbleBed_Primary_Loop.core.fuelModel[7].Fuel_kernel_center.port_b1.T", 
  "hTGR_PebbleBed_Primary_Loop.core.fuelModel[8].Fuel_kernel.port_b1.T", 
  "hTGR_PebbleBed_Primary_Loop.core.fuelModel[8].Fuel_kernel_center.port_b1.T"});
end dsmodelIterationSelect;
