within NHES.UsersGuide;
model Overview "Overview of the NHES Library"
  extends Modelica.Icons.Information;

  annotation (Documentation(info="<html>
<p>The NHES system began development back in 2014 at Idaho National Laboratory and is a collection of transient process models including Nuclear Power Plants, </p>
<p>Hydrogen Production Facilities, Rankine Based Balance of Plant systems, Thermal Energy Storage Technologies, Brackish Water Desalination, and Peaking units ranging</p>
<p>from Hydrogen Turbines to Natural Gas turbine peakers. </p>
<p><br>References: </p>
<p><b><span style=\"font-family: Times New Roman; font-size: 10pt; background-color: #ffffff;\">2017 Overview Document</span></b></p>
<ul>
<li><span style=\"font-family: Times New Roman;\"><a href=\"https://www.osti.gov/biblio/1408526-status-report-modelling-simulation-capabilities-nuclear-renewable-hybrid-energy-systems\">https://www.osti.gov/biblio/1408526-status-report-modelling-simulation-capabilities-nuclear-renewable-hybrid-energy-systems</a><span style=\"background-color: #ffffff;\">&nbsp;-- Rabiti, C., Epiney, A., Talbot, P., Kim, J. S., Bragg-Sitton, S., Alfonsi, A., Yigitoglu, A., Greenwood, S., Cetiner, S. M., Ganda, F., and Maronati, G. Status Report on Modelling and Simulation Capabilities for Nuclear-Renewable Hybrid Energy Systems. United States: N. p., 2017. Web. doi:10.2172/1408526.</span></li>
</ul>
<p><b><span style=\"font-family: Times New Roman; font-size: 10pt;\"><a name=\"user-content-component-literature\">C</a><span style=\"background-color: #ffffff;\">omponent Literature</span></b></p>
<ul>
<li><span style=\"font-family: Times New Roman;\"><a href=\"https://www.osti.gov/biblio/1569288-status-report-nuscale-module-developed-modelica-framework\">https://www.osti.gov/biblio/1569288-status-report-nuscale-module-developed-modelica-framework</a><span style=\"background-color: #ffffff;\">. -- Frick, Konor L. Status Report on the NuScale Module Developed in the Modelica Framework. United States: N. p., 2019. Web. doi:10.2172/1569288.</span></li>
<li><span style=\"font-family: Times New Roman;\"><a href=\"https://www.osti.gov/biblio/1333156-status-component-models-developed-modelica-framework-high-temperature-steam-electrolysis-plant-gas-turbine-power-plant\">https://www.osti.gov/biblio/1333156-status-component-models-developed-modelica-framework-high-temperature-steam-electrolysis-plant-gas-turbine-power-plant</a><span style=\"background-color: #ffffff;\">&nbsp;-- Suk Kim, Jong, McKellar, Michael, Bragg-Sitton, Shannon M., and Boardman, Richard D. Status on the Component Models Developed in the Modelica Framework: High-Temperature Steam Electrolysis Plant &amp; Gas Turbine Power Plant. United States: N. p., 2016. Web. doi:10.2172/1333156.</span></li>
<li><span style=\"font-family: Times New Roman;\"><a href=\"https://www.osti.gov/biblio/1468648-status-report-component-models-developed-modelica-framework-reverse-osmosis-desalination-plant-thermal-energy-storage\">https://www.osti.gov/biblio/1468648-status-report-component-models-developed-modelica-framework-reverse-osmosis-desalination-plant-thermal-energy-storage</a><span style=\"background-color: #ffffff;\">&nbsp;--Kim, Jong Suk, and Frick, Konor. Status Report on the Component Models Developed in the Modelica Framework: Reverse Osmosis Desalination Plant &amp; Thermal Energy Storage. United States: N. p., 2018. Web. doi:10.2172/1468648.</span></li>
<li><span style=\"font-family: Times New Roman;\"><a href=\"https://www.osti.gov/biblio/1333156-status-component-models-developed-modelica-framework-high-temperature-steam-electrolysis-plant-gas-turbine-power-plant\">https://www.osti.gov/biblio/1333156-status-component-models-developed-modelica-framework-high-temperature-steam-electrolysis-plant-gas-turbine-power-plant</a><span style=\"background-color: #ffffff;\">&nbsp;-- Suk Kim, Jong, McKellar, Michael, Bragg-Sitton, Shannon M., and Boardman, Richard D. Status on the Component Models Developed in the Modelica Framework: High-Temperature Steam Electrolysis Plant &amp; Gas Turbine Power Plant. United States: N. p., 2016. Web. doi:10.2172/1333156.</span></li>
</ul>
<p><b><span style=\"font-family: Times New Roman; font-size: 10pt;\"><a name=\"user-content-journal-articles-and-thesis-incorporated\">J</a><span style=\"background-color: #ffffff;\">ournal Articles and Thesis Incorporated</span></b></p>
<ul>
<li><span style=\"font-family: Times New Roman;\"><a href=\"https://www.osti.gov/biblio/1557660-design-operation-sensible-heat-peaking-unit-small-modular-reactors\">https://www.osti.gov/biblio/1557660-design-operation-sensible-heat-peaking-unit-small-modular-reactors</a><span style=\"background-color: #ffffff;\">&nbsp;-- Frick, Konor, Doster, Joseph Michael, and Bragg-Sitton, Shannon. Design and Operation of a Sensible Heat Peaking Unit for Small Modular Reactors. United States: N. p., 2018. Web. doi:10.1080/00295450.2018.1491181.</span></li>
<li><span style=\"font-family: Times New Roman;\"><a href=\"https://www.osti.gov/biblio/1557661-thermal-energy-storage-configurations-small-modular-reactor-load-shedding\">https://www.osti.gov/biblio/1557661-thermal-energy-storage-configurations-small-modular-reactor-load-shedding</a><span style=\"background-color: #ffffff;\">&nbsp;-- Frick, Konor, Misenheimer, Corey T., Doster, J. Michael, Terry, Stephen D., and Bragg-Sitton, Shannon. Thermal Energy Storage Configurations for Small Modular Reactor Load Shedding. United States: N. p., 2018. Web. doi:10.1080/00295450.2017.1420945.</span></li>
<li><span style=\"font-family: Times New Roman;\"><a href=\"https://www.osti.gov/biblio/1562960-dynamic-performance-analysis-high-temperature-steam-electrolysis-plant-integrated-within-nuclear-renewable-hybrid-energy-systems\">https://www.osti.gov/biblio/1562960-dynamic-performance-analysis-high-temperature-steam-electrolysis-plant-integrated-within-nuclear-renewable-hybrid-energy-systems</a><span style=\"background-color: #ffffff;\">&nbsp;-- Kim, Jong Suk, Boardman, Richard D., and Bragg-Sitton, Shannon M. Dynamic performance analysis of a high-temperature steam electrolysis plant integrated within nuclear-renewable hybrid energy systems. United Kingdom: N. p., 2018. Web. doi:10.1016/j.apenergy.2018.07.060.</span></li>
<li><span style=\"font-family: Times New Roman;\"><a href=\"https://www.osti.gov/biblio/1357452-modeling-control-dynamic-performance-analysis-reverse-osmosis-desalination-plant-integrated-within-hybrid-energy-systems\">https://www.osti.gov/biblio/1357452-modeling-control-dynamic-performance-analysis-reverse-osmosis-desalination-plant-integrated-within-hybrid-energy-systems</a><span style=\"background-color: #ffffff;\">. Kim, Jong Suk, Chen, Jun, and Garcia, Humberto E. Modeling, control, and dynamic performance analysis of a reverse osmosis desalination plant integrated within hybrid energy systems. United States: N. p., 2016. Web. doi:10.1016/j.energy.2016.05.050.</span></li>
</ul>
</html>"));
end Overview;
