model dsmodelIterationSelect
  extends NHES.Systems.IndustrialProcess.HighTempSteamElectrolysis.Examples.HTSE_TightlyCoupled_PowerCtrl_Test;
  annotation(__Dymola_SimulationIterationVariables={"IP.controlledSOEC.SOECstack.XcathodeIn[1]",
   "IP.controlledSOEC.SOECstack.XcathodeIn[2]", "IP.controlledSOEC.SOECstack.ycathodeOut[1]",
   "IP.hEX_cathodeGasRecup_ROM.tube_out.p", "IP.toppingHeater_cathodeGas.heatedPipe.cp_mean",
   "IP.toppingHeater_cathodeGas.heatedPipe.M", "IP.toppingHeater_cathodeGas.heatedPipe.rho_mean",
   "IP.toppingHeater_cathodeGas.heatedPipe.T_mean", "IP.controlledSOEC.SOECstack.cpC",
   "IP.controlledSOEC.SOECstack.N_H2O_cathode", "IP.controlledSOEC.SOECstack.N_H2_cathode",
   "IP.controlledSOEC.SOECstack.rho_CathodeAvg", "IP.controlledSOEC.SOECstack.TCavg",
   "IP.idealRecycle_H2.actuator_wH2_in.y", "IP.actuator_wCathode_in.y", 
  "IP.hEX_cathodeGasRecup_ROM.shell_in.m_flow", "IP.hEX_nuclearHeatCathodeGasRecup_ROM.hTube_out",
   "IP.hEX_cathodeGasRecup_ROM.tube_out.h_outflow", "IP.toppingHeater_cathodeGas.port_b.h_outflow",
   "IP.hEX_anodeGasRecup_ROM.tube_out.p", "IP.controlledSOEC.SOECstack.yanodeOut[2]",
   "IP.toppingHeater_anodeGas.heatedPipe.cp_mean", "IP.toppingHeater_anodeGas.heatedPipe.M",
   "IP.toppingHeater_anodeGas.heatedPipe.rho_mean", "IP.toppingHeater_anodeGas.heatedPipe.T_mean",
   "IP.controlledSOEC.SOECstack.cpA", "IP.controlledSOEC.SOECstack.N_O2_anode", 
  "IP.controlledSOEC.SOECstack.N_N2_anode", "IP.controlledSOEC.SOECstack.rho_AnodeAvg",
   "IP.controlledSOEC.SOECstack.TAavg", "IP.actuator_wAnode_in.y", 
  "IP.hEX_nuclearHeatAnodeGasRecup_ROM.tube_out.h_outflow", "IP.hEX_anodeGasRecup_ROM.tube_out.h_outflow",
   "IP.toppingHeater_anodeGas.port_b.h_outflow", "IP.controlledSOEC.SOECstack.lossActOPanode",
   "IP.controlledSOEC.SOECstack.lossActOPcathode", "IP.controlledSOEC.SOECstack.cathodeFlangeOut.h_outflow",
   "der(IP.toppingHeater_cathodeGas.heatedPipe.T_mean)", "der(IP.controlledSOEC.SOECstack.TCavg)",
   "der(IP.controlledSOEC.SOECstack.XcathodeIn[2])", "der(IP.controlledSOEC.SOECstack.XcathodeAvg[2])",
   "der(IP.controlledSOEC.SOECstack.XcathodeAvg[1])", "IP.controlledSOEC.SOECstack.wCathodeIn",
   "der(IP.hEX_cathodeGasRecup_ROM.tube_out.p)", "der(IP.controlledSOEC.SOECstack.XcathodeIn[1])",
   "der(IP.controlledSOEC.SOECstack.ycathodeOut[1])", "IP.controlledSOEC.ctrlAnodeOut.m_flow",
   "IP.controlledSOEC.ctrlAnodeOut.h_outflow", "IP.hEX_cathodeGasRecup_ROM.shell_out.h_outflow",
   "IP.hEX_anodeGasRecup_ROM.shell_out.h_outflow", "IP.TCV_anodeGas.dp", 
  "IP.TCV_cathodeGas.dp", "IP.hEX_nuclearHeatAnodeGasRecup_ROM.shell_out.h_outflow",
   "IP.hEX_nuclearHeatCathodeGasRecup_ROM.shell_out.h_outflow", "IP.port_b.h_outflow",
   "IP.cascadeCtrl_yH2.mixer_H2Recycled.T"});
end dsmodelIterationSelect;
