#define DYNEventSpecial
#if !defined(FMU_SOURCE_SINGLE_UNIT) && !defined(BUILDFMU) && !defined(DYMOSIM) && !defined(STANDALONE_DYMOSIM) && !defined(Matlab6)
#define DYMOSIM
#if defined(GODESS2) && !defined(GODESS)
#define GODESS
#endif
#endif

  /* DSblock model generated by Dymola from Modelica model Modelica.Mechanics.Rotational.Examples.CoupledClutches
 Dymola Version 2026x, 2025-10-10 translated this at Mon Jun  8 21:39:38 2026

   */

#include "matrixop.h"
#include "matrixop.c"
static int DymArraysV1[1]={1};
static int DymArrays2[1]={2};
static int DymArraysV0[2]={1, 2};
/* Declaration of C-structs */
struct DymStruc0;
struct DymStruc0 {
  int  id_0member;
};
DYMOLA_STATIC struct DymStruc0 DymStruc0_construct(int   id_02) {
  struct DymStruc0 dummy_0;
  dummy_0.id_0member = id_02;
  return dummy_0;
}
/* Prototypes for functions used in model */
#include "ModelicaStandardTables.h"
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getTable1DValue_M(struct 
  DymStruc0 tableID0_0, int  icol0_0, double  u0_0);
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getTable1DValueNoDer_M(
  struct DymStruc0 tableID0_0, int  icol0_0, double  u0_0);
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getTable1DValueNoDer2_M(
  struct DymStruc0 tableID0_0, int  icol0_0, double  u0_0);
DYMOLA_STATIC struct DymStruc0  Modelica_Blocks_Types_ExternalCombiTable1D_M(
  const char*  tableName0_0, const char*  fileName0_0, RealArray   table0_0, 
  IntegerArray   columns0_0, int  smoothness0_0, int  extrapolation0_0, int  
  verboseRead0_0, const char*  delimiter0_0, int  nHeaderLines0_0, 
  int id_, int alwaysMakeNew_);
DYMOLA_STATIC void Modelica_Blocks_Types_ExternalCombiTable1D_destructor_M(
  void* externalCombiTable1D0_0);
/* Codes used in model */

/* Flattened Modelica model:

function Modelica.Blocks.Tables.Internal.getTable1DValue
discrete input Modelica.Blocks.Types.ExternalCombiTable1D tableID;
input Integer icol "Column number";
discrete input Real u "Abscissa value";
discrete output Real y "Interpolated value";

external "C" equation
y = ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u) annotation(Include="#include \"ModelicaStandardTables.h\"", Library={"ModelicaIO", "ModelicaMatIO", "ModelicaStandardTables", "zlib"}, IncludeDirectory="modelica://Modelica/Resources/C-Sources", LibraryDirectory="modelica://Modelica/Resources/Library");
annotation(derivative=Modelica.Blocks.Tables.Internal.getDerTable1DValue);
end Modelica.Blocks.Tables.Internal.getTable1DValue;

  */
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getTable1DValue_M(struct 
  DymStruc0 tableID0_0, int  icol0_0, double  u0_0) {
  PushContext("Modelica.Blocks.Tables.Internal.getTable1DValue")
  {
    /* Declare outputs and temporaries */
    double   y0_0;
    y0_0=0;
    /* Start of real code */
    {
      y0_0 = (ModelicaStandardTables_CombiTable1D_getValue)(externalTable_[
        tableID0_0.id_0member].obj_, icol0_0, u0_0);
      }
    /* Output section */
    PopContext()
    return y0_0;
  }}

/* Flattened Modelica model:

function Modelica.Blocks.Tables.Internal.getTable1DValueNoDer
discrete input Modelica.Blocks.Types.ExternalCombiTable1D tableID;
input Integer icol "Column number";
discrete input Real u "Abscissa value";
discrete output Real y "Interpolated value";

external "C" equation
y = ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u) annotation(Include="#include \"ModelicaStandardTables.h\"", Library={"ModelicaIO", "ModelicaMatIO", "ModelicaStandardTables", "zlib"}, IncludeDirectory="modelica://Modelica/Resources/C-Sources", LibraryDirectory="modelica://Modelica/Resources/Library");
end Modelica.Blocks.Tables.Internal.getTable1DValueNoDer;

  */
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getTable1DValueNoDer_M(
  struct DymStruc0 tableID0_0, int  icol0_0, double  u0_0) {
  PushContext("Modelica.Blocks.Tables.Internal.getTable1DValueNoDer")
  {
    /* Declare outputs and temporaries */
    double   y0_0;
    y0_0=0;
    /* Start of real code */
    {
      y0_0 = (ModelicaStandardTables_CombiTable1D_getValue)(externalTable_[
        tableID0_0.id_0member].obj_, icol0_0, u0_0);
      }
    /* Output section */
    PopContext()
    return y0_0;
  }}

/* Flattened Modelica model:

function Modelica.Blocks.Tables.Internal.getTable1DValueNoDer2
discrete input Modelica.Blocks.Types.ExternalCombiTable1D tableID;
input Integer icol "Column number";
discrete input Real u "Abscissa value";
discrete output Real y "Interpolated value";

external "C" equation
y = ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u) annotation(Include="#include \"ModelicaStandardTables.h\"", Library={"ModelicaIO", "ModelicaMatIO", "ModelicaStandardTables", "zlib"}, IncludeDirectory="modelica://Modelica/Resources/C-Sources", LibraryDirectory="modelica://Modelica/Resources/Library");
annotation(derivative=Modelica.Blocks.Tables.Internal.getDerTable1DValueNoDer);
end Modelica.Blocks.Tables.Internal.getTable1DValueNoDer2;

  */
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getTable1DValueNoDer2_M(
  struct DymStruc0 tableID0_0, int  icol0_0, double  u0_0) {
  PushContext("Modelica.Blocks.Tables.Internal.getTable1DValueNoDer2")
  {
    /* Declare outputs and temporaries */
    double   y0_0;
    y0_0=0;
    /* Start of real code */
    {
      y0_0 = (ModelicaStandardTables_CombiTable1D_getValue)(externalTable_[
        tableID0_0.id_0member].obj_, icol0_0, u0_0);
      }
    /* Output section */
    PopContext()
    return y0_0;
  }}

/* Flattened Modelica model:

function constructor
input String tableName "Table name";
input String fileName "File name";
discrete input Real table[:, :];
input Integer columns[:];
input Modelica.Blocks.Types.Smoothness smoothness;
input Modelica.Blocks.Types.Extrapolation extrapolation(start = Modelica.Blocks.Types.Extrapolation.LastTwoPoints);
input Boolean verboseRead(start = true) "= true: Print info message; = false: No info message";
input String delimiter(start = ",") "Column delimiter character for CSV file";
input Integer nHeaderLines(start = 0) "Number of header lines to ignore for CSV file";
discrete output Modelica.Blocks.Types.ExternalCombiTable1D externalCombiTable1D;

external "C" equation
externalCombiTable1D = ModelicaStandardTables_CombiTable1D_init3(fileName, tableName, table, size(table, 1), size(table, 2), columns, size(columns, 1), smoothness, extrapolation, verboseRead, delimiter, nHeaderLines) annotation(Include="#include \"ModelicaStandardTables.h\"", Library={"ModelicaIO", "ModelicaMatIO", "ModelicaStandardTables", "zlib"}, IncludeDirectory="modelica://Modelica/Resources/C-Sources", LibraryDirectory="modelica://Modelica/Resources/Library");
end constructor;

  */
DYMOLA_STATIC struct DymStruc0  Modelica_Blocks_Types_ExternalCombiTable1D_M(
  const char*  tableName0_0, const char*  fileName0_0, RealArray   table0_0, 
  IntegerArray   columns0_0, int  smoothness0_0, int  extrapolation0_0, int  
  verboseRead0_0, const char*  delimiter0_0, int  nHeaderLines0_0, 
  int id_, int alwaysMakeNew_) {
  PushContext("Modelica.Blocks.Types.ExternalCombiTable1D")
  {
    /* Declare outputs and temporaries */
    struct DymStruc0  externalCombiTable1D0_0;
    externalCombiTable1D0_0.id_0member=0;
    /* Start of real code */
    {
      externalCombiTable1D0_0.id_0member=id_;
      if (externalTable_[id_].destructor_ && externalTable_[id_].obj_ && alwaysMakeNew_) {
      void*x_=externalTable_[id_].obj_;
      externalTable_[id_].obj_=0;
      (*(externalTable_[id_].destructor_))(x_);
      } else if (!externalTable_[id_].destructor_) {externalTable_[id_].obj_=0;}
      #if (defined(_OPENMP) && !defined(DISABLE_DYMOLA_OPENMP))
      if (!(externalTable_[id_].haveLock_)) {omp_init_lock(&(externalTable_[id_].lockExternal_));externalTable_[id_].haveLock_=1;}
      #endif
      externalTable_[id_].destructor_=Modelica_Blocks_Types_ExternalCombiTable1D_destructor_M;

        if (!externalTable_[id_].obj_) externalTable_[id_].obj_ = (
        ModelicaStandardTables_CombiTable1D_init3)(fileName0_0, tableName0_0, 
        table0_0.data, table0_0.dims[1-1], table0_0.dims[2-1], columns0_0.data, 
        columns0_0.dims[1-1], smoothness0_0, extrapolation0_0, verboseRead0_0, 
        delimiter0_0, nHeaderLines0_0);
      }
    /* Output section */
    PopContext()
    return externalCombiTable1D0_0;
  }}

/* Flattened Modelica model:

function destructor
discrete input Modelica.Blocks.Types.ExternalCombiTable1D externalCombiTable1D;

external "C" equation
ModelicaStandardTables_CombiTable1D_close(externalCombiTable1D) annotation(Include="#include \"ModelicaStandardTables.h\"", Library={"ModelicaIO", "ModelicaMatIO", "ModelicaStandardTables", "zlib"}, IncludeDirectory="modelica://Modelica/Resources/C-Sources", LibraryDirectory="modelica://Modelica/Resources/Library");
end destructor;

  */
DYMOLA_STATIC void Modelica_Blocks_Types_ExternalCombiTable1D_destructor_M(
  void* externalCombiTable1D0_0) {
  PushContext("Modelica.Blocks.Types.ExternalCombiTable1D.destructor")
  {
    /* Declare outputs and temporaries */
    /* Start of real code */
    {
      (ModelicaStandardTables_CombiTable1D_close)(externalCombiTable1D0_0);
      }
    /* Output section */
    PopContext()
    return ;
  }}
/* DSblock C-code: */

#define NX_    8
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    102
#define NWC_   38
#define NWP_   47
#define NWD_   70
#define NP_    42
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 1327213652
#define NHash2_ 357606716
#define NHash3_ 0
#define NI_    0
#define NRelF_ 21
#define NRel_  21
#define NTim_  4
#define NSamp_ 0
#define NCons_ 0
#define NA_    54
#define SizePre_ 12
#define SizeEq_ 4
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 9
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 117
#define NGlobalHelpI_ 12
#define NSparse_ 0
#ifndef NExternalObject_
#define NExternalObject_ 3
#endif
#include "moutil.h"
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="Modelica.Mechanics.Rotational.Examples.CoupledClutches";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "C:/Users/RIGBAC/AppData/Roaming/DassaultSystemes/Dymola/dymola.lic";
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[14]={3 , 6 , 1 , 2 , 3 , 4 , 5 , 7 , 1 , 6 , 1 , 8
   , 0 , 0};
static int QJacobianGrp0[9]={2, 4, 4, 4, 0, 4, 0, 4, 0};
static int QJacobianGrp1[9]={0, 6, 0, 6, 6, 6, 0, 6, 0};
static int QJacobianGrp2[9]={0, 8, 0, 8, 0, 8, 8, 8, 0};
DYMOLA_STATIC struct QJacobianTag_ QJacobianGC2_[4]={
{0, QJacobianGrp0},{0, QJacobianGrp1},{0, QJacobianGrp2},{0,0}};
DYMOLA_STATIC double QJacobianCD_[9]={0  , 44 , 55 , 66 , 77 , 88 , 90 , 110 , 99};
#include "dsblock1.c"

/* Define variable names. */

#define Sections_

TranslatedEquations
InitialSection

InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
InitialBoundSection
{
  struct DymStruc0 dummy_DymStruc0;
  dummy_DymStruc0 = (PushModelContext(1,"Modelica.Blocks.Types.ExternalCombiTable1D(\"NoName\", \"NoName\", clutch1.mu_pos, {2}, clutch1.smoothness, Modelica.Blocks.Types.Extrapolation.LastTwoPoints, false, \",\", 0, 0, 1)")
    Modelica_Blocks_Types_ExternalCombiTable1D_M("NoName", "NoName", 
    RealTemporaryDense2( &DYNX(DP_,4), 2, DymArraysV0), IntegerTemporaryDense2( 
    DymArrays2, 1, DymArraysV1), (Integer)(DYNX(DP_,6)), 2, false, ",", 0, 0, 1));
  DYNX(W_,38) = dummy_DymStruc0.id_0member;
PopModelContext();
}
BoundParameterSection
DYNX(W_,39) = IF DYNX(DP_,6) == 3 THEN (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTable1DValueNoDer(\nclutch1.tableID, \n1, \n0)")
  Modelica_Blocks_Tables_Internal_getTable1DValueNoDer_M(DymStruc0_construct(
  (Integer)(DYNX(W_,38))), 1, 0)) ELSE IF DYNX(DP_,6) == 1 THEN (PushModelContext(1,
  "Modelica.Blocks.Tables.Internal.getTable1DValueNoDer2(\nclutch1.tableID, \n1, \n0)")
  Modelica_Blocks_Tables_Internal_getTable1DValueNoDer2_M(DymStruc0_construct(
  (Integer)(DYNX(W_,38))), 1, 0)) ELSE (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTable1DValue(\nclutch1.tableID, \n1, \n0)")
  Modelica_Blocks_Tables_Internal_getTable1DValue_M(DymStruc0_construct(
  (Integer)(DYNX(W_,38))), 1, 0));
PopModelContext();
DYNX(W_,40) = DYNX(DP_,1);
InitialBoundSection
{
  struct DymStruc0 dummy_DymStruc0;
  dummy_DymStruc0 = (PushModelContext(1,"Modelica.Blocks.Types.ExternalCombiTable1D(\"NoName\", \"NoName\", clutch2.mu_pos, {2}, clutch2.smoothness, Modelica.Blocks.Types.Extrapolation.LastTwoPoints, false, \",\", 0, 1, 1)")
    Modelica_Blocks_Types_ExternalCombiTable1D_M("NoName", "NoName", 
    RealTemporaryDense2( &DYNX(DP_,19), 2, DymArraysV0), IntegerTemporaryDense2( 
    DymArrays2, 1, DymArraysV1), (Integer)(DYNX(DP_,21)), 2, false, ",", 0, 1, 1));
  DYNX(W_,41) = dummy_DymStruc0.id_0member;
PopModelContext();
}
BoundParameterSection
DYNX(W_,42) = IF DYNX(DP_,21) == 3 THEN (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTable1DValueNoDer(\nclutch2.tableID, \n1, \n0)")
  Modelica_Blocks_Tables_Internal_getTable1DValueNoDer_M(DymStruc0_construct(
  (Integer)(DYNX(W_,41))), 1, 0)) ELSE IF DYNX(DP_,21) == 1 THEN 
  (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTable1DValueNoDer2(\nclutch2.tableID, \n1, \n0)")
  Modelica_Blocks_Tables_Internal_getTable1DValueNoDer2_M(DymStruc0_construct(
  (Integer)(DYNX(W_,41))), 1, 0)) ELSE (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTable1DValue(\nclutch2.tableID, \n1, \n0)")
  Modelica_Blocks_Tables_Internal_getTable1DValue_M(DymStruc0_construct(
  (Integer)(DYNX(W_,41))), 1, 0));
PopModelContext();
InitialBoundSection
{
  struct DymStruc0 dummy_DymStruc0;
  dummy_DymStruc0 = (PushModelContext(1,"Modelica.Blocks.Types.ExternalCombiTable1D(\"NoName\", \"NoName\", clutch3.mu_pos, {2}, clutch3.smoothness, Modelica.Blocks.Types.Extrapolation.LastTwoPoints, false, \",\", 0, 2, 1)")
    Modelica_Blocks_Types_ExternalCombiTable1D_M("NoName", "NoName", 
    RealTemporaryDense2( &DYNX(DP_,27), 2, DymArraysV0), IntegerTemporaryDense2( 
    DymArrays2, 1, DymArraysV1), (Integer)(DYNX(DP_,29)), 2, false, ",", 0, 2, 1));
  DYNX(W_,43) = dummy_DymStruc0.id_0member;
PopModelContext();
}
BoundParameterSection
DYNX(W_,44) = IF DYNX(DP_,29) == 3 THEN (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTable1DValueNoDer(\nclutch3.tableID, \n1, \n0)")
  Modelica_Blocks_Tables_Internal_getTable1DValueNoDer_M(DymStruc0_construct(
  (Integer)(DYNX(W_,43))), 1, 0)) ELSE IF DYNX(DP_,29) == 1 THEN 
  (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTable1DValueNoDer2(\nclutch3.tableID, \n1, \n0)")
  Modelica_Blocks_Tables_Internal_getTable1DValueNoDer2_M(DymStruc0_construct(
  (Integer)(DYNX(W_,43))), 1, 0)) ELSE (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTable1DValue(\nclutch3.tableID, \n1, \n0)")
  Modelica_Blocks_Tables_Internal_getTable1DValue_M(DymStruc0_construct(
  (Integer)(DYNX(W_,43))), 1, 0));
PopModelContext();
DYNX(W_,45) = DYNX(DP_,0);
DYNX(W_,46) = DYNX(DP_,2);
InitialSection
InitialStartSection
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialBoundSection
DYNX(Aux_,0) = DYNX(W_,51);
DYNX(Aux_,1) = DYNX(W_,49);
DYNX(Aux_,2) = DYNX(W_,48);
DYNX(Aux_,3) = DYNX(W_,59);
DYNX(Aux_,4) = DYNX(W_,57);
DYNX(Aux_,5) = DYNX(W_,56);
DYNX(Aux_,6) = DYNX(W_,67);
DYNX(Aux_,7) = DYNX(W_,65);
DYNX(Aux_,8) = DYNX(W_,64);
InitialSection
InitialSection2
DYNX(X_,3) = DYNX(W_,83)-DYNX(X_,1);
DYNX(X_,5) = DYNX(W_,92)-DYNX(W_,83);
DYNX(X_,7) = DYNX(W_,100)-DYNX(W_,92);
DYNX(X_,6) = DYNX(W_,99)-DYNX(W_,91);
DYNX(X_,4) = DYNX(W_,91)-DYNX(W_,82);
DYNX(X_,2) = DYNX(W_,82)-DYNX(X_,0);
InitialSection
InitialSection2
DYNX(W_,51) = DYNX(Aux_,0);
DYNX(W_,49) = DYNX(Aux_,1);
DYNX(W_,48) = DYNX(Aux_,2);
DYNX(W_,59) = DYNX(Aux_,3);
DYNX(W_,57) = DYNX(Aux_,4);
DYNX(W_,56) = DYNX(Aux_,5);
DYNX(W_,67) = DYNX(Aux_,6);
DYNX(W_,65) = DYNX(Aux_,7);
DYNX(W_,64) = DYNX(Aux_,8);
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
DYNX(W_,69) = DYNX(DP_,40)+(IF LessTime(DYNX(W_,46), 0) THEN 0 ELSE DYNX(DP_,39));
DYNX(W_,68) = DYNX(DP_,32)*DYNX(W_,69);
DYNX(W_,63) = LessEqual(DYNX(W_,68),"clutch3.fn", 0,"0", 0);
DYNX(W_,61) = DYNX(W_,44)*DYNX(DP_,31)*DYNX(W_,68);
DYNX(W_,62) = DYNX(DP_,30)*DYNX(W_,61);
DYNX(W_,52) = DYNX(DP_,17)+(IF LessTime(DYNX(W_,40), 1) THEN 0 ELSE DYNX(DP_,16));
DYNX(W_,60) = DYNX(DP_,24)*DYNX(W_,52);
DYNX(W_,55) = LessEqual(DYNX(W_,60),"clutch2.fn", 0,"0", 1);
DYNX(W_,70) = DYNX(DP_,14)+(IF LessTime(DYNX(DP_,15), 2) THEN 0 ELSE 
  DYNX(DP_,11)*sin(6.283185307179586*DYNX(DP_,12)*(DYNTime-DYNX(DP_,15))+
  DYNX(DP_,13)));
DYNX(W_,78) = DYNX(DP_,37)+(IF LessTime(DYNX(DP_,38), 3) THEN 0 ELSE 
  DYNX(DP_,35)*sin(6.283185307179586*DYNX(W_,45)*(DYNTime-DYNX(DP_,38))+
  DYNX(DP_,36)));
DYNX(W_,77) = DYNX(DP_,9)*DYNX(W_,78);
DYNX(W_,47) = LessEqual(DYNX(W_,77),"clutch1.fn", 0,"0", 2);
DYNX(W_,72) = DYNX(W_,39)*DYNX(DP_,8)*DYNX(W_,77);
DYNX(W_,73) = DYNX(DP_,7)*DYNX(W_,72);
DYNX(W_,53) = DYNX(W_,42)*DYNX(DP_,23)*DYNX(W_,60);
DYNX(W_,54) = DYNX(DP_,22)*DYNX(W_,53);

MixedSystemOfEquations(22, DYNX(DYNhelp,0))
  DYNX(W_,88) = IF DYNX(W_,56) THEN 1 ELSE IF DYNX(W_,57) THEN 1 ELSE IF PRE(
    DYNX(W_,59), 3) == 1 THEN 1 ELSE -1;
  DYNX(W_,89) = IF DYNX(W_,56) THEN 1 ELSE IF DYNX(W_,57) THEN -1 ELSE IF PRE(
    DYNX(W_,59), 3) == 1 THEN 1 ELSE -1;
  DYNX(W_,87) = DYNX(W_,89)*(IF DYNX(DP_,21) == 3 THEN (PushModelContext(1,
    "Modelica.Blocks.Tables.Internal.getTable1DValueNoDer(\nclutch2.tableID, \n1, \nclutch2.table_signs[1]*clutch2.w_rel)")
    Modelica_Blocks_Tables_Internal_getTable1DValueNoDer_M(DymStruc0_construct(
    (Integer)(DYNX(W_,41))), 1, DYNX(W_,88)*DYNX(X_,5))) ELSE IF DYNX(DP_,21)
     == 1 THEN (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTable1DValueNoDer2(\nclutch2.tableID, \n1, \nclutch2.table_signs[1]*clutch2.w_rel)")
    Modelica_Blocks_Tables_Internal_getTable1DValueNoDer2_M(DymStruc0_construct(
    (Integer)(DYNX(W_,41))), 1, DYNX(W_,88)*DYNX(X_,5))) ELSE (PushModelContext(1,
    "Modelica.Blocks.Tables.Internal.getTable1DValue(\nclutch2.tableID, \n1, \nclutch2.table_signs[1]*clutch2.w_rel)")
    Modelica_Blocks_Tables_Internal_getTable1DValue_M(DymStruc0_construct(
    (Integer)(DYNX(W_,41))), 1, DYNX(W_,88)*DYNX(X_,5))));
  PopModelContext();
  DYNX(W_,79) = IF DYNX(W_,48) THEN 1 ELSE IF DYNX(W_,49) THEN 1 ELSE IF PRE(
    DYNX(W_,51), 1) == 1 THEN 1 ELSE -1;
  DYNX(W_,80) = IF DYNX(W_,48) THEN 1 ELSE IF DYNX(W_,49) THEN -1 ELSE IF PRE(
    DYNX(W_,51), 1) == 1 THEN 1 ELSE -1;
  DYNX(W_,76) = DYNX(W_,80)*(IF DYNX(DP_,6) == 3 THEN (PushModelContext(1,
    "Modelica.Blocks.Tables.Internal.getTable1DValueNoDer(\nclutch1.tableID, \n1, \nclutch1.table_signs[1]*clutch1.w_rel)")
    Modelica_Blocks_Tables_Internal_getTable1DValueNoDer_M(DymStruc0_construct(
    (Integer)(DYNX(W_,38))), 1, DYNX(W_,79)*DYNX(X_,3))) ELSE IF DYNX(DP_,6) == 1
     THEN (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTable1DValueNoDer2(\nclutch1.tableID, \n1, \nclutch1.table_signs[1]*clutch1.w_rel)")
    Modelica_Blocks_Tables_Internal_getTable1DValueNoDer2_M(DymStruc0_construct(
    (Integer)(DYNX(W_,38))), 1, DYNX(W_,79)*DYNX(X_,3))) ELSE (PushModelContext(1,
    "Modelica.Blocks.Tables.Internal.getTable1DValue(\nclutch1.tableID, \n1, \nclutch1.table_signs[1]*clutch1.w_rel)")
    Modelica_Blocks_Tables_Internal_getTable1DValue_M(DymStruc0_construct(
    (Integer)(DYNX(W_,38))), 1, DYNX(W_,79)*DYNX(X_,3))));
  PopModelContext();
  DYNX(W_,98) = IF DYNX(W_,64) THEN 1 ELSE IF DYNX(W_,65) THEN -1 ELSE IF PRE(
    DYNX(W_,67), 5) == 1 THEN 1 ELSE -1;
  DYNX(W_,97) = IF DYNX(W_,64) THEN 1 ELSE IF DYNX(W_,65) THEN 1 ELSE IF PRE(
    DYNX(W_,67), 5) == 1 THEN 1 ELSE -1;
  DYNX(W_,96) = DYNX(W_,98)*(IF DYNX(DP_,29) == 3 THEN (PushModelContext(1,
    "Modelica.Blocks.Tables.Internal.getTable1DValueNoDer(\nclutch3.tableID, \n1, \nclutch3.table_signs[1]*clutch3.w_rel)")
    Modelica_Blocks_Tables_Internal_getTable1DValueNoDer_M(DymStruc0_construct(
    (Integer)(DYNX(W_,43))), 1, DYNX(W_,97)*DYNX(X_,7))) ELSE IF DYNX(DP_,29)
     == 1 THEN (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTable1DValueNoDer2(\nclutch3.tableID, \n1, \nclutch3.table_signs[1]*clutch3.w_rel)")
    Modelica_Blocks_Tables_Internal_getTable1DValueNoDer2_M(DymStruc0_construct(
    (Integer)(DYNX(W_,43))), 1, DYNX(W_,97)*DYNX(X_,7))) ELSE (PushModelContext(1,
    "Modelica.Blocks.Tables.Internal.getTable1DValue(\nclutch3.tableID, \n1, \nclutch3.table_signs[1]*clutch3.w_rel)")
    Modelica_Blocks_Tables_Internal_getTable1DValue_M(DymStruc0_construct(
    (Integer)(DYNX(W_,43))), 1, DYNX(W_,97)*DYNX(X_,7))));
  PopModelContext();

   /* Linear system of equations to solve. */
  /* Tag: simulation.linear[1] */
  /* Introducing 13 common subexpressions whereof 5 are global used in 15
     expressions */
  /* Of the common subexpressions 10 are reals, 3 are integers, and 0
     are booleans. */
  DYNX(DYNhelp,22) = IF DYNX(W_,50) THEN 0.0 ELSE IF DYNX(W_,47) THEN 0 ELSE 
    DYNX(W_,76)*DYNX(DP_,8)*DYNX(W_,77);
  DYNX(DYNhelp,23) = PRE(DYNX(W_,67), 5);
  DYNX(DYNhelp,24) = PRE(DYNX(W_,59), 3);
  DYNX(DYNhelp,25) = IF DYNX(W_,58) THEN 0 ELSE IF DYNX(W_,55) THEN 0.0 ELSE IF 
    DYNX(W_,56) THEN  -DYNX(W_,54) ELSE IF DYNX(W_,57) THEN DYNX(W_,54) ELSE IF 
    DYNX(DYNhelp,24) == 1 THEN  -DYNX(W_,54) ELSE IF DYNX(DYNhelp,24) == -1
     THEN DYNX(W_,54) ELSE  -(IF DYNX(X_,5) > 0 THEN 1 ELSE IF DYNX(X_,5) < 0
     THEN -1 ELSE 0)*DYNX(W_,54);
  DYNX(DYNhelp,26) = PRE(DYNX(W_,51), 1);
  DYNX(DYNhelp,27) = IF DYNX(W_,50) THEN 0 ELSE IF DYNX(W_,47) THEN 0.0 ELSE IF 
    DYNX(W_,48) THEN  -DYNX(W_,73) ELSE IF DYNX(W_,49) THEN DYNX(W_,73) ELSE IF 
    DYNX(DYNhelp,26) == 1 THEN  -DYNX(W_,73) ELSE IF DYNX(DYNhelp,26) == -1
     THEN DYNX(W_,73) ELSE  -(IF DYNX(X_,3) > 0 THEN 1 ELSE IF DYNX(X_,3) < 0
     THEN -1 ELSE 0)*DYNX(W_,73);
  DYNX(DYNhelp,28) = IF DYNX(W_,66) THEN 0.0 ELSE IF DYNX(W_,63) THEN 0 ELSE 
    DYNX(W_,96)*DYNX(DP_,31)*DYNX(W_,68);
  DYNX(DYNhelp,29) = IF DYNX(W_,58) THEN 0.0 ELSE IF DYNX(W_,55) THEN 0 ELSE 
    DYNX(W_,87)*DYNX(DP_,23)*DYNX(W_,60);
  /* Automatic tearing of linear system of 13 simultaneous equations
  gave a linear system of 4 equations for numerical solution.*/
  {
    const char*const varnames_[]={"J1.der(w)", "clutch3.sa", "clutch2.sa", 
      "clutch1.sa"};
    DidLinearSystemOfEquationsDisc(J, b, y, 4, DYNX(DYNhelp,30), 64, 
      DYNX(did_->helpvari_vec,0), 12);
    /* Jacobian depending on discrete variables */
    /* Special case for simplified event handling */
    #if defined(EventIterate_) && (EventIterate_==0)
    SetNeedFactor(J);
    #else
    if (IfLinearSystemOfEquationsDisc()
    ||DYNEvent) SetNeedFactor(J);
    #endif
    if (NeedFactor(J)) {
      UpLinearSystemOfEquationsDisc()
      MatrixZeros(J);
      DYNX(DYNhelp,94) = IF DYNX(W_,50) THEN 1.0 ELSE 0.0;
      DYNX(DYNhelp,95) = IF DYNX(W_,66) THEN 1.0 ELSE 0.0;
      DYNX(DYNhelp,96) = IF DYNX(W_,58) THEN 0.0 ELSE 1.0;
      DYNX(DYNhelp,97) = IF DYNX(W_,50) THEN 0.0 ELSE 1.0;
      DYNX(DYNhelp,98) = IF DYNX(W_,58) THEN 1.0 ELSE 0.0;
      SetMatrixLeading(J, 1, 1, 4, DYNX(DP_,3));
      SetMatrixLeading(J, 1, 4, 4, (-1.0)*DYNX(DYNhelp,94));
      SetMatrixLeading(J, 2, 1, 4, DYNX(DP_,34));
      SetMatrixLeading(J, 2, 2, 4, DYNX(DP_,34)*(IF DYNX(W_,66) THEN 0.0 ELSE 
        1.0)+DYNX(DYNhelp,95));
      SetMatrixLeading(J, 2, 3, 4, DYNX(DP_,34)*DYNX(DYNhelp,96));
      SetMatrixLeading(J, 2, 4, 4, DYNX(DP_,34)*DYNX(DYNhelp,97));
      SetMatrixLeading(J, 3, 1, 4, DYNX(DP_,26));
      SetMatrixLeading(J, 3, 2, 4, (-1.0)*DYNX(DYNhelp,95));
      SetMatrixLeading(J, 3, 3, 4, DYNX(DP_,26)*DYNX(DYNhelp,96)+
        DYNX(DYNhelp,98));
      SetMatrixLeading(J, 3, 4, 4, DYNX(DP_,26)*DYNX(DYNhelp,97));
      SetMatrixLeading(J, 4, 1, 4, DYNX(DP_,18));
      SetMatrixLeading(J, 4, 3, 4, (-1.0)*DYNX(DYNhelp,98));
      SetMatrixLeading(J, 4, 4, 4, DYNX(DYNhelp,94)+DYNX(DP_,18)*
        DYNX(DYNhelp,97));
    }
    SetVector(b, 1, DYNX(W_,70)+DYNX(DYNhelp,22));
    SetVector(b, 2,  -(DYNX(DP_,34)*(IF DYNX(W_,66) THEN 0 ELSE IF DYNX(W_,63)
       THEN 0.0 ELSE IF DYNX(W_,64) THEN  -DYNX(W_,62) ELSE IF DYNX(W_,65) THEN 
      DYNX(W_,62) ELSE IF DYNX(DYNhelp,23) == 1 THEN  -DYNX(W_,62) ELSE IF 
      DYNX(DYNhelp,23) == -1 THEN DYNX(W_,62) ELSE  -(IF DYNX(X_,7) > 0 THEN 1
       ELSE IF DYNX(X_,7) < 0 THEN -1 ELSE 0)*DYNX(W_,62))+DYNX(DP_,34)*
      DYNX(DYNhelp,25)+DYNX(DP_,34)*DYNX(DYNhelp,27)+DYNX(DYNhelp,28)));
    SetVector(b, 3,  -(DYNX(DP_,26)*DYNX(DYNhelp,25)+DYNX(DP_,26)*
      DYNX(DYNhelp,27)-DYNX(DYNhelp,28)+DYNX(DYNhelp,29)));
    SetVector(b, 4, DYNX(DYNhelp,29)-(DYNX(DYNhelp,22)+DYNX(DP_,18)*
      DYNX(DYNhelp,27)));
    SetVector(y, 1, RememberSimple_(DYNX(F_,1), 0));
    SetVector(y, 2, RememberSimple_(DYNX(W_,94), 1));
    SetVector(y, 3, RememberSimple_(DYNX(W_,85), 2));
    SetVector(y, 4, RememberSimple_(DYNX(W_,74), 3));
    SolveLinearSystemOfEquationsMixed(J, b, y, 1, "simulation.linear[1]");
    DYNX(F_,1) = GetVector(y, 1);
    DYNX(W_,94) = GetVector(y, 2);
    DYNX(W_,85) = GetVector(y, 3);
    DYNX(W_,74) = GetVector(y, 4);
    EndStaticLinearSystemOfEquations(J);
  }
  DYNX(W_,71) = IF DYNX(W_,50) THEN DYNX(W_,74) ELSE IF DYNX(W_,47) THEN 0 ELSE 
    DYNX(W_,76)*DYNX(DP_,8)*DYNX(W_,77);
  DYNX(F_,7) = IF DYNX(W_,66) THEN 0 ELSE IF DYNX(W_,63) THEN DYNX(W_,94) ELSE 
    IF DYNX(W_,64) THEN DYNX(W_,94)-DYNX(W_,62) ELSE IF DYNX(W_,65) THEN 
    DYNX(W_,94)+DYNX(W_,62) ELSE IF DYNX(DYNhelp,23) == 1 THEN DYNX(W_,94)-
    DYNX(W_,62) ELSE IF DYNX(DYNhelp,23) == -1 THEN DYNX(W_,94)+DYNX(W_,62)
     ELSE DYNX(W_,94)-(IF DYNX(X_,7) > 0 THEN 1 ELSE IF DYNX(X_,7) < 0 THEN -1
     ELSE 0)*DYNX(W_,62);
  DYNX(F_,5) = IF DYNX(W_,58) THEN 0 ELSE IF DYNX(W_,55) THEN DYNX(W_,85) ELSE 
    IF DYNX(W_,56) THEN DYNX(W_,85)-DYNX(W_,54) ELSE IF DYNX(W_,57) THEN 
    DYNX(W_,85)+DYNX(W_,54) ELSE IF DYNX(DYNhelp,24) == 1 THEN DYNX(W_,85)-
    DYNX(W_,54) ELSE IF DYNX(DYNhelp,24) == -1 THEN DYNX(W_,85)+DYNX(W_,54)
     ELSE DYNX(W_,85)-(IF DYNX(X_,5) > 0 THEN 1 ELSE IF DYNX(X_,5) < 0 THEN -1
     ELSE 0)*DYNX(W_,54);
  DYNX(F_,3) = IF DYNX(W_,50) THEN 0 ELSE IF DYNX(W_,47) THEN DYNX(W_,74) ELSE 
    IF DYNX(W_,48) THEN DYNX(W_,74)-DYNX(W_,73) ELSE IF DYNX(W_,49) THEN 
    DYNX(W_,74)+DYNX(W_,73) ELSE IF DYNX(DYNhelp,26) == 1 THEN DYNX(W_,74)-
    DYNX(W_,73) ELSE IF DYNX(DYNhelp,26) == -1 THEN DYNX(W_,74)+DYNX(W_,73)
     ELSE DYNX(W_,74)-(IF DYNX(X_,3) > 0 THEN 1 ELSE IF DYNX(X_,3) < 0 THEN -1
     ELSE 0)*DYNX(W_,73);
  DYNX(W_,84) = DYNX(F_,3)+DYNX(F_,1);
  DYNX(W_,93) = DYNX(F_,5)+DYNX(W_,84);
  DYNX(W_,101) = DYNX(F_,7)+DYNX(W_,93);
  DYNX(W_,90) = IF DYNX(W_,66) THEN DYNX(W_,94) ELSE IF DYNX(W_,63) THEN 0 ELSE 
    DYNX(W_,96)*DYNX(DP_,31)*DYNX(W_,68);
  DYNX(W_,81) = IF DYNX(W_,58) THEN DYNX(W_,85) ELSE IF DYNX(W_,55) THEN 0 ELSE 
    DYNX(W_,87)*DYNX(DP_,23)*DYNX(W_,60);
   /* End of Equation Block */ 


  MixedModeStartBoolean
  UpdateVariableNamed(DYNX(W_,48),"clutch1.startForward", PRE(DYNX(W_,51), 1)
     == 0 AND Greater(DYNX(W_,74),"clutch1.sa", IF PRE(DYNX(W_,48), 6) THEN 
    RealBmin(DYNX(W_,73), DYNX(W_,72)) ELSE DYNX(W_,73),"(if pre(clutch1.startForward) then min(clutch1.tau0_max, clutch1.tau0) else clutch1.tau0_max)",
     3) OR PRE(DYNX(W_,51), 1) == -1 AND Greater(DYNX(X_,3),"clutch1.w_relfric",
     DYNX(DP_,10),"clutch1.w_small", 4) OR initial() AND Greater(DYNX(X_,3),
    "clutch1.w_relfric", 0,"0", 5));
  UpdateVariableNamed(DYNX(W_,49),"clutch1.startBackward", PRE(DYNX(W_,51), 1)
     == 0 AND Less(DYNX(W_,74),"clutch1.sa", IF PRE(DYNX(W_,49), 7) THEN 
    RealBmax( -DYNX(W_,73),  -DYNX(W_,72)) ELSE  -DYNX(W_,73),"(if pre(clutch1.startBackward) then max( -clutch1.tau0_max,  -clutch1.tau0) else  -clutch1.tau0_max)",
     6) OR PRE(DYNX(W_,51), 1) == 1 AND Less(DYNX(X_,3),"clutch1.w_relfric",  -
    DYNX(DP_,10)," -clutch1.w_small", 7) OR initial() AND Less(DYNX(X_,3),
    "clutch1.w_relfric", 0,"0", 8));
  UpdateVariableNamed(DYNX(W_,50),"clutch1.locked",  NOT DYNX(W_,47) AND  NOT (
    PRE(DYNX(W_,51), 1) == 1 OR DYNX(W_,48) OR PRE(DYNX(W_,51), 1) == -1 OR 
    DYNX(W_,49)));
  UpdateVariableNamed(DYNX(W_,56),"clutch2.startForward", PRE(DYNX(W_,59), 3)
     == 0 AND Greater(DYNX(W_,85),"clutch2.sa", IF PRE(DYNX(W_,56), 8) THEN 
    RealBmin(DYNX(W_,54), DYNX(W_,53)) ELSE DYNX(W_,54),"(if pre(clutch2.startForward) then min(clutch2.tau0_max, clutch2.tau0) else clutch2.tau0_max)",
     9) OR PRE(DYNX(W_,59), 3) == -1 AND Greater(DYNX(X_,5),"clutch2.w_relfric",
     DYNX(DP_,25),"clutch2.w_small", 10) OR initial() AND Greater(DYNX(X_,5),
    "clutch2.w_relfric", 0,"0", 11));
  UpdateVariableNamed(DYNX(W_,57),"clutch2.startBackward", PRE(DYNX(W_,59), 3)
     == 0 AND Less(DYNX(W_,85),"clutch2.sa", IF PRE(DYNX(W_,57), 9) THEN 
    RealBmax( -DYNX(W_,54),  -DYNX(W_,53)) ELSE  -DYNX(W_,54),"(if pre(clutch2.startBackward) then max( -clutch2.tau0_max,  -clutch2.tau0) else  -clutch2.tau0_max)",
     12) OR PRE(DYNX(W_,59), 3) == 1 AND Less(DYNX(X_,5),"clutch2.w_relfric",  -
    DYNX(DP_,25)," -clutch2.w_small", 13) OR initial() AND Less(DYNX(X_,5),
    "clutch2.w_relfric", 0,"0", 14));
  UpdateVariableNamed(DYNX(W_,58),"clutch2.locked",  NOT DYNX(W_,55) AND  NOT (
    PRE(DYNX(W_,59), 3) == 1 OR DYNX(W_,56) OR PRE(DYNX(W_,59), 3) == -1 OR 
    DYNX(W_,57)));
  UpdateVariableNamed(DYNX(W_,64),"clutch3.startForward", PRE(DYNX(W_,67), 5)
     == 0 AND Greater(DYNX(W_,94),"clutch3.sa", IF PRE(DYNX(W_,64), 10) THEN 
    RealBmin(DYNX(W_,62), DYNX(W_,61)) ELSE DYNX(W_,62),"(if pre(clutch3.startForward) then min(clutch3.tau0_max, clutch3.tau0) else clutch3.tau0_max)",
     15) OR PRE(DYNX(W_,67), 5) == -1 AND Greater(DYNX(X_,7),"clutch3.w_relfric",
     DYNX(DP_,33),"clutch3.w_small", 16) OR initial() AND Greater(DYNX(X_,7),
    "clutch3.w_relfric", 0,"0", 17));
  UpdateVariableNamed(DYNX(W_,65),"clutch3.startBackward", PRE(DYNX(W_,67), 5)
     == 0 AND Less(DYNX(W_,94),"clutch3.sa", IF PRE(DYNX(W_,65), 11) THEN 
    RealBmax( -DYNX(W_,62),  -DYNX(W_,61)) ELSE  -DYNX(W_,62),"(if pre(clutch3.startBackward) then max( -clutch3.tau0_max,  -clutch3.tau0) else  -clutch3.tau0_max)",
     18) OR PRE(DYNX(W_,67), 5) == 1 AND Less(DYNX(X_,7),"clutch3.w_relfric",  -
    DYNX(DP_,33)," -clutch3.w_small", 19) OR initial() AND Less(DYNX(X_,7),
    "clutch3.w_relfric", 0,"0", 20));
  UpdateVariableNamed(DYNX(W_,66),"clutch3.locked",  NOT DYNX(W_,63) AND  NOT (
    PRE(DYNX(W_,67), 5) == 1 OR DYNX(W_,64) OR PRE(DYNX(W_,67), 5) == -1 OR 
    DYNX(W_,65)));
  MixedModeInit(18, DYNX(DYNhelp,99))
  ThetaMixedCross(0,3)
  ThetaMixedCross(1,4)
  ThetaMixedCross(2,5)
  ThetaMixedCross(3,6)
  ThetaMixedCross(4,7)
  ThetaMixedCross(5,8)
  ThetaMixedCross(6,9)
  ThetaMixedCross(7,10)
  ThetaMixedCross(8,11)
  ThetaMixedCross(9,12)
  ThetaMixedCross(10,13)
  ThetaMixedCross(11,14)
  ThetaMixedCross(12,15)
  ThetaMixedCross(13,16)
  ThetaMixedCross(14,17)
  ThetaMixedCross(15,18)
  ThetaMixedCross(16,19)
  ThetaMixedCross(17,20)
  MixedModeEndBoolean
  UpdateReal(DYNX(W_,88), 1)
  UpdateReal(DYNX(W_,89), 2)
  UpdateReal(DYNX(W_,87), 3)
  UpdateReal(DYNX(W_,79), 4)
  UpdateReal(DYNX(W_,80), 5)
  UpdateReal(DYNX(W_,76), 6)
  UpdateReal(DYNX(W_,74), 7)
  UpdateReal(DYNX(F_,1), 8)
  UpdateReal(DYNX(F_,3), 9)
  UpdateReal(DYNX(W_,71), 10)
  UpdateReal(DYNX(W_,84), 11)
  UpdateReal(DYNX(F_,5), 12)
  UpdateReal(DYNX(W_,85), 13)
  UpdateReal(DYNX(W_,81), 14)
  UpdateReal(DYNX(W_,93), 15)
  UpdateReal(DYNX(W_,97), 16)
  UpdateReal(DYNX(W_,98), 17)
  UpdateReal(DYNX(W_,96), 18)
  UpdateReal(DYNX(W_,94), 19)
  UpdateReal(DYNX(W_,90), 20)
  UpdateReal(DYNX(W_,101), 21)
  UpdateReal(DYNX(F_,7), 22)
EndMixedSystemOfEquations

DYNX(F_,0) = DYNX(X_,1);
DYNX(F_,6) = DYNX(X_,7);
DYNX(F_,4) = DYNX(X_,5);
DYNX(F_,2) = DYNX(X_,3);

AcceptedSection1
DYNX(W_,59) = IF DYNX(W_,55) THEN 2 ELSE IF (PRE(DYNX(W_,59), 3) == 1 OR PRE(
  DYNX(W_,59), 3) == 2 OR DYNX(W_,56)) AND Greater(DYNX(X_,5),"clutch2.w_relfric",
   0,"0", 11) THEN 1 ELSE IF (PRE(DYNX(W_,59), 3) == -1 OR PRE(DYNX(W_,59), 3)
   == 2 OR DYNX(W_,57)) AND Less(DYNX(X_,5),"clutch2.w_relfric", 0,"0", 14)
   THEN -1 ELSE 0;
DYNX(W_,51) = IF DYNX(W_,47) THEN 2 ELSE IF (PRE(DYNX(W_,51), 1) == 1 OR PRE(
  DYNX(W_,51), 1) == 2 OR DYNX(W_,48)) AND Greater(DYNX(X_,3),"clutch1.w_relfric",
   0,"0", 5) THEN 1 ELSE IF (PRE(DYNX(W_,51), 1) == -1 OR PRE(DYNX(W_,51), 1)
   == 2 OR DYNX(W_,49)) AND Less(DYNX(X_,3),"clutch1.w_relfric", 0,"0", 8) THEN -1
   ELSE 0;
DYNX(W_,67) = IF DYNX(W_,63) THEN 2 ELSE IF (PRE(DYNX(W_,67), 5) == 1 OR PRE(
  DYNX(W_,67), 5) == 2 OR DYNX(W_,64)) AND Greater(DYNX(X_,7),"clutch3.w_relfric",
   0,"0", 17) THEN 1 ELSE IF (PRE(DYNX(W_,67), 5) == -1 OR PRE(DYNX(W_,67), 5)
   == 2 OR DYNX(W_,65)) AND Less(DYNX(X_,7),"clutch3.w_relfric", 0,"0", 20)
   THEN -1 ELSE 0;

AcceptedSection2
DYNX(W_,82) = DYNX(X_,2)+DYNX(X_,0);
DYNX(W_,91) = DYNX(X_,4)+DYNX(W_,82);
DYNX(W_,99) = DYNX(X_,6)+DYNX(W_,91);
DYNX(W_,83) = DYNX(X_,3)+DYNX(X_,1);
DYNX(W_,92) = DYNX(X_,5)+DYNX(W_,83);
DYNX(W_,100) = DYNX(X_,7)+DYNX(W_,92);
DYNX(W_,75) = DYNX(W_,71)*DYNX(X_,3);
DYNX(W_,86) = DYNX(W_,81)*DYNX(X_,5);
DYNX(W_,95) = DYNX(W_,90)*DYNX(X_,7);

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include "dsblock6.c"

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("f", "Frequency of sine function to invoke clutch1 [Hz]", 0, \
0.2, 0.0,0.0,0.0,0,560)
DeclareParameter("T2", "Time when clutch2 is invoked [s]", 1, 0.4, 0.0,0.0,0.0,0,560)
DeclareParameter("T3", "Time when clutch3 is invoked [s]", 2, 0.9, 0.0,0.0,0.0,0,560)
DeclareAlias2("J1.flange_a.phi", "Absolute rotation angle of flange [rad|deg]", \
"J1.phi", 1, 1, 0, 4)
DeclareVariable("J1.flange_a.tau", "Cut torque in the flange [N.m]", 70, 0.0, \
0.0,0.0,0.0,0,776)
DeclareAlias2("J1.flange_b.phi", "Absolute rotation angle of flange [rad|deg]", \
"J1.phi", 1, 1, 0, 4)
DeclareVariable("J1.flange_b.tau", "Cut torque in the flange [N.m]", 71, 0.0, \
0.0,0.0,0.0,0,776)
DeclareParameter("J1.J", "Moment of inertia [kg.m2]", 3, 1, 0.0,1.7976931348623157E+308,\
0.0,0,560)
DeclareVariable("J1.stateSelect", "Priority to use phi and w as states [:#(type=StateSelect)]",\
 0, 3, 1.0,5.0,0.0,0,1541)
DeclareState("J1.phi", "Absolute rotation angle of component [rad|deg]", 0, 0, \
0.0,0.0,0.0,0,560)
DeclareDerivative("J1.der(phi)", "der(Absolute rotation angle of component) [rad/s]",\
 0, 0.0, 0.0,0.0,0.0,0,8704)
DeclareState("J1.w", "Absolute angular velocity of component (= der(phi)) [rad/s]",\
 1, 10, 0.0,0.0,0.0,0,560)
DeclareDerivative("J1.der(w)", "der(Absolute angular velocity of component (= der(phi))) [rad/s2]",\
 1, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("J1.a", "Absolute angular acceleration of component (= der(w)) [rad/s2]",\
 "J1.der(w)", 1, 6, 1, 0)
DeclareVariable("torque.useSupport", "= true, if support flange enabled, otherwise implicitly grounded [:#(type=Boolean)]",\
 1, true, 0.0,0.0,0.0,0,1539)
DeclareAlias2("torque.flange.phi", "Absolute rotation angle of flange [rad|deg]",\
 "J1.phi", 1, 1, 0, 4)
DeclareAlias2("torque.flange.tau", "Cut torque in the flange [N.m]", \
"J1.flange_a.tau", -1, 5, 70, 132)
DeclareAlias2("torque.support.phi", "Absolute rotation angle of flange [rad|deg]",\
 "fixed.phi0", 1, 7, 41, 4)
DeclareAlias2("torque.support.tau", "Cut torque in the flange [N.m]", \
"J1.flange_a.tau", 1, 5, 70, 132)
DeclareAlias2("torque.phi_support", "Absolute angle of support flange [rad|deg]",\
 "fixed.phi0", 1, 7, 41, 1024)
DeclareAlias2("torque.tau", "Accelerating torque acting at flange (= -flange.tau) [N.m]",\
 "J1.flange_a.tau", 1, 5, 70, 0)
DeclareState("clutch1.phi_rel", "Relative rotation angle (= flange_b.phi - flange_a.phi) [rad|deg]",\
 2, 0, 0.0,0.0,0.0001,0,544)
DeclareDerivative("clutch1.der(phi_rel)", "der(Relative rotation angle (= flange_b.phi - flange_a.phi)) [rad/s]",\
 2, 0.0, 0.0,0.0,0.0,0,8704)
DeclareState("clutch1.w_rel", "Relative angular velocity (= der(phi_rel)) [rad/s]",\
 3, 0, 0.0,0.0,0.0,0,544)
DeclareDerivative("clutch1.der(w_rel)", "der(Relative angular velocity (= der(phi_rel))) [rad/s2]",\
 3, 0, 0.0,0.0,0.0,0,512)
DeclareAlias2("clutch1.a_rel", "Relative angular acceleration (= der(w_rel)) [rad/s2]",\
 "clutch1.der(w_rel)", 1, 6, 3, 0)
DeclareAlias2("clutch1.tau", "Torque between flanges (= flange_b.tau) [N.m]", \
"J1.flange_b.tau", 1, 5, 71, 0)
DeclareAlias2("clutch1.flange_a.phi", "Absolute rotation angle of flange [rad|deg]",\
 "J1.phi", 1, 1, 0, 4)
DeclareAlias2("clutch1.flange_a.tau", "Cut torque in the flange [N.m]", \
"J1.flange_b.tau", -1, 5, 71, 132)
DeclareAlias2("clutch1.flange_b.phi", "Absolute rotation angle of flange [rad|deg]",\
 "J2.phi", 1, 5, 82, 4)
DeclareAlias2("clutch1.flange_b.tau", "Cut torque in the flange [N.m]", \
"J1.flange_b.tau", 1, 5, 71, 132)
DeclareVariable("clutch1.phi_nominal", "Nominal value of phi_rel (used for scaling) [rad|rad]",\
 2, 0.0001, 0.0,1.7976931348623157E+308,0.0,0,513)
DeclareVariable("clutch1.stateSelect", "Priority to use phi_rel and w_rel as states [:#(type=StateSelect)]",\
 3, 4, 1.0,5.0,0.0,0,1541)
DeclareParameter("clutch1.mu_pos[1, 1]", "Positive sliding friction coefficient [-] as function of w_rel [rad/s] (w_rel>=0)",\
 4, 0.0, 0.0,0.0,0.0,0,560)
DeclareParameter("clutch1.mu_pos[1, 2]", "Positive sliding friction coefficient [-] as function of w_rel [rad/s] (w_rel>=0)",\
 5, 0.5, 0.0,0.0,0.0,0,560)
DeclareParameter("clutch1.smoothness", "Smoothness of table interpolation in mu_pos [:#(type=Modelica.Blocks.Types.Smoothness)]",\
 6, 1, 1.0,6.0,0.0,0,564)
DeclareParameter("clutch1.peak", "Peak for maximum value of mu at w==0 (mu0_max = peak*mu_pos[1,2]) [1]",\
 7, 1.1, 1.0,1.7976931348623157E+308,0.0,0,560)
DeclareParameter("clutch1.cgeo", "Geometry constant containing friction distribution assumption",\
 8, 1, 0.0,1.7976931348623157E+308,0.0,0,560)
DeclareParameter("clutch1.fn_max", "Maximum normal force [N]", 9, 20, 0.0,\
1.7976931348623157E+308,0.0,0,560)
DeclareParameter("clutch1.w_small", "Relative angular velocity near to zero if jumps due to a reinit(..) of the velocity can occur (set to low value only if such impulses can occur) [rad/s]",\
 10, 10000000000.0, 0.0,0.0,0.0,0,560)
DeclareAlias2("clutch1.w_relfric", "Relative angular velocity between frictional surfaces [rad/s]",\
 "clutch1.w_rel", 1, 1, 3, 0)
DeclareAlias2("clutch1.a_relfric", "Relative angular acceleration between frictional surfaces [rad/s2]",\
 "clutch1.der(w_rel)", 1, 6, 3, 0)
DeclareVariable("clutch1.tau0", "Friction torque for w_relfric=0 and forward sliding [N.m]",\
 72, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("clutch1.tau0_max", "Maximum friction torque for w_relfric=0 and locked [N.m]",\
 73, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("clutch1.free", "= true, if frictional element is not active [:#(type=Boolean)]",\
 47, false, 0.0,0.0,0.0,0,642)
DeclareVariable("clutch1.sa", "Path parameter of friction characteristic tau = f(a_relfric) [1]",\
 74, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("clutch1.startForward", "= true, if w_relfric=0 and start of forward sliding [:#(type=Boolean)]",\
 48, false, 0.0,0.0,0.0,0,722)
DeclareVariable("clutch1.startBackward", "= true, if w_relfric=0 and start of backward sliding [:#(type=Boolean)]",\
 49, false, 0.0,0.0,0.0,0,722)
DeclareVariable("clutch1.locked", "= true, if w_rel=0 and not sliding [:#(type=Boolean)]",\
 50, false, 0.0,0.0,0.0,0,706)
DeclareVariable("clutch1.Unknown", "Value of mode is not known [:#(type=Integer)]",\
 4, 3, 0.0,0.0,0.0,0,517)
DeclareVariable("clutch1.Free", "Element is not active [:#(type=Integer)]", 5, 2,\
 0.0,0.0,0.0,0,517)
DeclareVariable("clutch1.Forward", "w_relfric > 0 (forward sliding) [:#(type=Integer)]",\
 6, 1, 0.0,0.0,0.0,0,517)
DeclareVariable("clutch1.Stuck", "w_relfric = 0 (forward sliding, locked or backward sliding) [:#(type=Integer)]",\
 7, 0, 0.0,0.0,0.0,0,517)
DeclareVariable("clutch1.Backward", "w_relfric < 0 (backward sliding) [:#(type=Integer)]",\
 8, -1, 0.0,0.0,0.0,0,517)
DeclareVariable("clutch1.mode", "Mode of friction (-1: backward sliding, 0: stuck, 1: forward sliding, 2: inactive, 3: unknown) [:#(type=Integer)]",\
 51, 3, -1.0,3.0,0.0,0,660)
DeclareVariable("clutch1.unitAngularAcceleration", "[rad/s2]", 9, 1, 0.0,0.0,0.0,\
0,1537)
DeclareVariable("clutch1.unitTorque", "[N.m]", 10, 1, 0.0,0.0,0.0,0,1537)
DeclareVariable("clutch1.useHeatPort", "= true, if heatPort is enabled [:#(type=Boolean)]",\
 11, false, 0.0,0.0,0.0,0,1539)
DeclareVariable("clutch1.lossPower", "Loss power leaving component via heatPort (> 0, if heat is flowing out of component) [W]",\
 75, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("clutch1.mu", "Friction coefficient", 76, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("clutch1.fn", "Normal force (fn=fn_max*f_normalized) [N]", 77, \
0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("clutch1.f_normalized", "Normalized force signal 0..1 (normal force = fn_max*f_normalized; clutch is engaged if > 0) [1]",\
 78, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("clutch1.tableID.id", "[:#(type=Integer)]", 38, 0, 0.0,0.0,0.0,0,2565)
DeclareVariable("clutch1.mu0", "Friction coefficient for w=0 and forward sliding",\
 39, 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("clutch1.table_signs[1]", "Signs for sliding friction coefficient table interpolation: [sign for w_rel, sign for mu] []",\
 79, 0.0, 0.0,0.0,0.0,0,2560)
DeclareVariable("clutch1.table_signs[2]", "Signs for sliding friction coefficient table interpolation: [sign for w_rel, sign for mu] []",\
 80, 0.0, 0.0,0.0,0.0,0,2560)
DeclareParameter("sin1.amplitude", "Amplitude of sine wave", 11, 10, 0.0,0.0,0.0,\
0,560)
DeclareParameter("sin1.f", "Frequency of sine wave [Hz]", 12, 5, 0.0,0.0,0.0,0,560)
DeclareParameter("sin1.phase", "Phase of sine wave [rad|deg]", 13, 0, 0.0,0.0,\
0.0,0,560)
DeclareVariable("sin1.continuous", "Make output continuous by starting at offset + amplitude*sin(phase) [:#(type=Boolean)]",\
 12, false, 0.0,0.0,0.0,0,515)
DeclareAlias2("sin1.y", "Connector of Real output signal [N.m]", \
"J1.flange_a.tau", 1, 5, 70, 0)
DeclareParameter("sin1.offset", "Offset of output signal y [N.m]", 14, 0, \
0.0,0.0,0.0,0,560)
DeclareParameter("sin1.startTime", "Output y = offset for time < startTime [s]",\
 15, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("step1.height", "Height of step [1]", 16, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("step1.y", "Connector of Real output signal [1]", 52, 0.0, \
0.0,0.0,0.0,0,640)
DeclareParameter("step1.offset", "Offset of output signal y [1]", 17, 0, \
0.0,0.0,0.0,0,560)
DeclareVariable("step1.startTime", "Output y = offset for time < startTime [s]",\
 40, 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("J2.flange_a.phi", "Absolute rotation angle of flange [rad|deg]", \
"J2.phi", 1, 5, 82, 4)
DeclareAlias2("J2.flange_a.tau", "Cut torque in the flange [N.m]", \
"J1.flange_b.tau", -1, 5, 71, 132)
DeclareAlias2("J2.flange_b.phi", "Absolute rotation angle of flange [rad|deg]", \
"J2.phi", 1, 5, 82, 4)
DeclareVariable("J2.flange_b.tau", "Cut torque in the flange [N.m]", 81, 0.0, \
0.0,0.0,0.0,0,776)
DeclareParameter("J2.J", "Moment of inertia [kg.m2]", 18, 1, 0.0,\
1.7976931348623157E+308,0.0,0,560)
DeclareVariable("J2.stateSelect", "Priority to use phi and w as states [:#(type=StateSelect)]",\
 13, 3, 1.0,5.0,0.0,0,1541)
DeclareVariable("J2.phi", "Absolute rotation angle of component [rad|deg]", 82, 0,\
 0.0,0.0,0.0,0,528)
DeclareAlias2("J2.der(phi)", "der(Absolute rotation angle of component) [rad/s]",\
 "J2.w", 1, 5, 83, 0)
DeclareVariable("J2.w", "Absolute angular velocity of component (= der(phi)) [rad/s]",\
 83, 0, 0.0,0.0,0.0,0,528)
DeclareVariable("J2.der(w)", "der(Absolute angular velocity of component (= der(phi))) [rad/s2]",\
 84, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("J2.a", "Absolute angular acceleration of component (= der(w)) [rad/s2]",\
 "J2.der(w)", 1, 5, 84, 0)
DeclareState("clutch2.phi_rel", "Relative rotation angle (= flange_b.phi - flange_a.phi) [rad|deg]",\
 4, 0, 0.0,0.0,0.0001,0,544)
DeclareDerivative("clutch2.der(phi_rel)", "der(Relative rotation angle (= flange_b.phi - flange_a.phi)) [rad/s]",\
 4, 0.0, 0.0,0.0,0.0,0,8704)
DeclareState("clutch2.w_rel", "Relative angular velocity (= der(phi_rel)) [rad/s]",\
 5, 0, 0.0,0.0,0.0,0,544)
DeclareDerivative("clutch2.der(w_rel)", "der(Relative angular velocity (= der(phi_rel))) [rad/s2]",\
 5, 0, 0.0,0.0,0.0,0,512)
DeclareAlias2("clutch2.a_rel", "Relative angular acceleration (= der(w_rel)) [rad/s2]",\
 "clutch2.der(w_rel)", 1, 6, 5, 0)
DeclareAlias2("clutch2.tau", "Torque between flanges (= flange_b.tau) [N.m]", \
"J2.flange_b.tau", 1, 5, 81, 0)
DeclareAlias2("clutch2.flange_a.phi", "Absolute rotation angle of flange [rad|deg]",\
 "J2.phi", 1, 5, 82, 4)
DeclareAlias2("clutch2.flange_a.tau", "Cut torque in the flange [N.m]", \
"J2.flange_b.tau", -1, 5, 81, 132)
DeclareAlias2("clutch2.flange_b.phi", "Absolute rotation angle of flange [rad|deg]",\
 "J3.phi", 1, 5, 91, 4)
DeclareAlias2("clutch2.flange_b.tau", "Cut torque in the flange [N.m]", \
"J2.flange_b.tau", 1, 5, 81, 132)
DeclareVariable("clutch2.phi_nominal", "Nominal value of phi_rel (used for scaling) [rad|rad]",\
 14, 0.0001, 0.0,1.7976931348623157E+308,0.0,0,513)
DeclareVariable("clutch2.stateSelect", "Priority to use phi_rel and w_rel as states [:#(type=StateSelect)]",\
 15, 4, 1.0,5.0,0.0,0,1541)
DeclareParameter("clutch2.mu_pos[1, 1]", "Positive sliding friction coefficient [-] as function of w_rel [rad/s] (w_rel>=0)",\
 19, 0.0, 0.0,0.0,0.0,0,560)
DeclareParameter("clutch2.mu_pos[1, 2]", "Positive sliding friction coefficient [-] as function of w_rel [rad/s] (w_rel>=0)",\
 20, 0.5, 0.0,0.0,0.0,0,560)
DeclareParameter("clutch2.smoothness", "Smoothness of table interpolation in mu_pos [:#(type=Modelica.Blocks.Types.Smoothness)]",\
 21, 1, 1.0,6.0,0.0,0,564)
DeclareParameter("clutch2.peak", "Peak for maximum value of mu at w==0 (mu0_max = peak*mu_pos[1,2]) [1]",\
 22, 1.1, 1.0,1.7976931348623157E+308,0.0,0,560)
DeclareParameter("clutch2.cgeo", "Geometry constant containing friction distribution assumption",\
 23, 1, 0.0,1.7976931348623157E+308,0.0,0,560)
DeclareParameter("clutch2.fn_max", "Maximum normal force [N]", 24, 20, 0.0,\
1.7976931348623157E+308,0.0,0,560)
DeclareParameter("clutch2.w_small", "Relative angular velocity near to zero if jumps due to a reinit(..) of the velocity can occur (set to low value only if such impulses can occur) [rad/s]",\
 25, 10000000000.0, 0.0,0.0,0.0,0,560)
DeclareAlias2("clutch2.w_relfric", "Relative angular velocity between frictional surfaces [rad/s]",\
 "clutch2.w_rel", 1, 1, 5, 0)
DeclareAlias2("clutch2.a_relfric", "Relative angular acceleration between frictional surfaces [rad/s2]",\
 "clutch2.der(w_rel)", 1, 6, 5, 0)
DeclareVariable("clutch2.tau0", "Friction torque for w_relfric=0 and forward sliding [N.m]",\
 53, 0.0, 0.0,0.0,0.0,0,640)
DeclareVariable("clutch2.tau0_max", "Maximum friction torque for w_relfric=0 and locked [N.m]",\
 54, 0.0, 0.0,0.0,0.0,0,640)
DeclareVariable("clutch2.free", "= true, if frictional element is not active [:#(type=Boolean)]",\
 55, false, 0.0,0.0,0.0,0,642)
DeclareVariable("clutch2.sa", "Path parameter of friction characteristic tau = f(a_relfric) [1]",\
 85, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("clutch2.startForward", "= true, if w_relfric=0 and start of forward sliding [:#(type=Boolean)]",\
 56, false, 0.0,0.0,0.0,0,722)
DeclareVariable("clutch2.startBackward", "= true, if w_relfric=0 and start of backward sliding [:#(type=Boolean)]",\
 57, false, 0.0,0.0,0.0,0,722)
DeclareVariable("clutch2.locked", "= true, if w_rel=0 and not sliding [:#(type=Boolean)]",\
 58, false, 0.0,0.0,0.0,0,706)
DeclareVariable("clutch2.Unknown", "Value of mode is not known [:#(type=Integer)]",\
 16, 3, 0.0,0.0,0.0,0,517)
DeclareVariable("clutch2.Free", "Element is not active [:#(type=Integer)]", 17, 2,\
 0.0,0.0,0.0,0,517)
DeclareVariable("clutch2.Forward", "w_relfric > 0 (forward sliding) [:#(type=Integer)]",\
 18, 1, 0.0,0.0,0.0,0,517)
DeclareVariable("clutch2.Stuck", "w_relfric = 0 (forward sliding, locked or backward sliding) [:#(type=Integer)]",\
 19, 0, 0.0,0.0,0.0,0,517)
DeclareVariable("clutch2.Backward", "w_relfric < 0 (backward sliding) [:#(type=Integer)]",\
 20, -1, 0.0,0.0,0.0,0,517)
DeclareVariable("clutch2.mode", "Mode of friction (-1: backward sliding, 0: stuck, 1: forward sliding, 2: inactive, 3: unknown) [:#(type=Integer)]",\
 59, 3, -1.0,3.0,0.0,0,660)
DeclareVariable("clutch2.unitAngularAcceleration", "[rad/s2]", 21, 1, 0.0,0.0,\
0.0,0,1537)
DeclareVariable("clutch2.unitTorque", "[N.m]", 22, 1, 0.0,0.0,0.0,0,1537)
DeclareVariable("clutch2.useHeatPort", "= true, if heatPort is enabled [:#(type=Boolean)]",\
 23, false, 0.0,0.0,0.0,0,1539)
DeclareVariable("clutch2.lossPower", "Loss power leaving component via heatPort (> 0, if heat is flowing out of component) [W]",\
 86, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("clutch2.mu", "Friction coefficient", 87, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("clutch2.fn", "Normal force (fn=fn_max*f_normalized) [N]", 60, \
0.0, 0.0,0.0,0.0,0,640)
DeclareAlias2("clutch2.f_normalized", "Normalized force signal 0..1 (normal force = fn_max*f_normalized; clutch is engaged if > 0) [1]",\
 "step1.y", 1, 5, 52, 0)
DeclareVariable("clutch2.tableID.id", "[:#(type=Integer)]", 41, 0, 0.0,0.0,0.0,0,2565)
DeclareVariable("clutch2.mu0", "Friction coefficient for w=0 and forward sliding",\
 42, 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("clutch2.table_signs[1]", "Signs for sliding friction coefficient table interpolation: [sign for w_rel, sign for mu] []",\
 88, 0.0, 0.0,0.0,0.0,0,2560)
DeclareVariable("clutch2.table_signs[2]", "Signs for sliding friction coefficient table interpolation: [sign for w_rel, sign for mu] []",\
 89, 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("J3.flange_a.phi", "Absolute rotation angle of flange [rad|deg]", \
"J3.phi", 1, 5, 91, 4)
DeclareAlias2("J3.flange_a.tau", "Cut torque in the flange [N.m]", \
"J2.flange_b.tau", -1, 5, 81, 132)
DeclareAlias2("J3.flange_b.phi", "Absolute rotation angle of flange [rad|deg]", \
"J3.phi", 1, 5, 91, 4)
DeclareVariable("J3.flange_b.tau", "Cut torque in the flange [N.m]", 90, 0.0, \
0.0,0.0,0.0,0,776)
DeclareParameter("J3.J", "Moment of inertia [kg.m2]", 26, 1, 0.0,\
1.7976931348623157E+308,0.0,0,560)
DeclareVariable("J3.stateSelect", "Priority to use phi and w as states [:#(type=StateSelect)]",\
 24, 3, 1.0,5.0,0.0,0,1541)
DeclareVariable("J3.phi", "Absolute rotation angle of component [rad|deg]", 91, 0,\
 0.0,0.0,0.0,0,528)
DeclareAlias2("J3.der(phi)", "der(Absolute rotation angle of component) [rad/s]",\
 "J3.w", 1, 5, 92, 0)
DeclareVariable("J3.w", "Absolute angular velocity of component (= der(phi)) [rad/s]",\
 92, 0, 0.0,0.0,0.0,0,528)
DeclareVariable("J3.der(w)", "der(Absolute angular velocity of component (= der(phi))) [rad/s2]",\
 93, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("J3.a", "Absolute angular acceleration of component (= der(w)) [rad/s2]",\
 "J3.der(w)", 1, 5, 93, 0)
DeclareState("clutch3.phi_rel", "Relative rotation angle (= flange_b.phi - flange_a.phi) [rad|deg]",\
 6, 0, 0.0,0.0,0.0001,0,544)
DeclareDerivative("clutch3.der(phi_rel)", "der(Relative rotation angle (= flange_b.phi - flange_a.phi)) [rad/s]",\
 6, 0.0, 0.0,0.0,0.0,0,8704)
DeclareState("clutch3.w_rel", "Relative angular velocity (= der(phi_rel)) [rad/s]",\
 7, 0, 0.0,0.0,0.0,0,544)
DeclareDerivative("clutch3.der(w_rel)", "der(Relative angular velocity (= der(phi_rel))) [rad/s2]",\
 7, 0, 0.0,0.0,0.0,0,512)
DeclareAlias2("clutch3.a_rel", "Relative angular acceleration (= der(w_rel)) [rad/s2]",\
 "clutch3.der(w_rel)", 1, 6, 7, 0)
DeclareAlias2("clutch3.tau", "Torque between flanges (= flange_b.tau) [N.m]", \
"J3.flange_b.tau", 1, 5, 90, 0)
DeclareAlias2("clutch3.flange_a.phi", "Absolute rotation angle of flange [rad|deg]",\
 "J3.phi", 1, 5, 91, 4)
DeclareAlias2("clutch3.flange_a.tau", "Cut torque in the flange [N.m]", \
"J3.flange_b.tau", -1, 5, 90, 132)
DeclareAlias2("clutch3.flange_b.phi", "Absolute rotation angle of flange [rad|deg]",\
 "J4.phi", 1, 5, 99, 4)
DeclareAlias2("clutch3.flange_b.tau", "Cut torque in the flange [N.m]", \
"J3.flange_b.tau", 1, 5, 90, 132)
DeclareVariable("clutch3.phi_nominal", "Nominal value of phi_rel (used for scaling) [rad|rad]",\
 25, 0.0001, 0.0,1.7976931348623157E+308,0.0,0,513)
DeclareVariable("clutch3.stateSelect", "Priority to use phi_rel and w_rel as states [:#(type=StateSelect)]",\
 26, 4, 1.0,5.0,0.0,0,1541)
DeclareParameter("clutch3.mu_pos[1, 1]", "Positive sliding friction coefficient [-] as function of w_rel [rad/s] (w_rel>=0)",\
 27, 0.0, 0.0,0.0,0.0,0,560)
DeclareParameter("clutch3.mu_pos[1, 2]", "Positive sliding friction coefficient [-] as function of w_rel [rad/s] (w_rel>=0)",\
 28, 0.5, 0.0,0.0,0.0,0,560)
DeclareParameter("clutch3.smoothness", "Smoothness of table interpolation in mu_pos [:#(type=Modelica.Blocks.Types.Smoothness)]",\
 29, 1, 1.0,6.0,0.0,0,564)
DeclareParameter("clutch3.peak", "Peak for maximum value of mu at w==0 (mu0_max = peak*mu_pos[1,2]) [1]",\
 30, 1.1, 1.0,1.7976931348623157E+308,0.0,0,560)
DeclareParameter("clutch3.cgeo", "Geometry constant containing friction distribution assumption",\
 31, 1, 0.0,1.7976931348623157E+308,0.0,0,560)
DeclareParameter("clutch3.fn_max", "Maximum normal force [N]", 32, 20, 0.0,\
1.7976931348623157E+308,0.0,0,560)
DeclareParameter("clutch3.w_small", "Relative angular velocity near to zero if jumps due to a reinit(..) of the velocity can occur (set to low value only if such impulses can occur) [rad/s]",\
 33, 10000000000.0, 0.0,0.0,0.0,0,560)
DeclareAlias2("clutch3.w_relfric", "Relative angular velocity between frictional surfaces [rad/s]",\
 "clutch3.w_rel", 1, 1, 7, 0)
DeclareAlias2("clutch3.a_relfric", "Relative angular acceleration between frictional surfaces [rad/s2]",\
 "clutch3.der(w_rel)", 1, 6, 7, 0)
DeclareVariable("clutch3.tau0", "Friction torque for w_relfric=0 and forward sliding [N.m]",\
 61, 0.0, 0.0,0.0,0.0,0,640)
DeclareVariable("clutch3.tau0_max", "Maximum friction torque for w_relfric=0 and locked [N.m]",\
 62, 0.0, 0.0,0.0,0.0,0,640)
DeclareVariable("clutch3.free", "= true, if frictional element is not active [:#(type=Boolean)]",\
 63, false, 0.0,0.0,0.0,0,642)
DeclareVariable("clutch3.sa", "Path parameter of friction characteristic tau = f(a_relfric) [1]",\
 94, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("clutch3.startForward", "= true, if w_relfric=0 and start of forward sliding [:#(type=Boolean)]",\
 64, false, 0.0,0.0,0.0,0,722)
DeclareVariable("clutch3.startBackward", "= true, if w_relfric=0 and start of backward sliding [:#(type=Boolean)]",\
 65, false, 0.0,0.0,0.0,0,722)
DeclareVariable("clutch3.locked", "= true, if w_rel=0 and not sliding [:#(type=Boolean)]",\
 66, false, 0.0,0.0,0.0,0,706)
DeclareVariable("clutch3.Unknown", "Value of mode is not known [:#(type=Integer)]",\
 27, 3, 0.0,0.0,0.0,0,517)
DeclareVariable("clutch3.Free", "Element is not active [:#(type=Integer)]", 28, 2,\
 0.0,0.0,0.0,0,517)
DeclareVariable("clutch3.Forward", "w_relfric > 0 (forward sliding) [:#(type=Integer)]",\
 29, 1, 0.0,0.0,0.0,0,517)
DeclareVariable("clutch3.Stuck", "w_relfric = 0 (forward sliding, locked or backward sliding) [:#(type=Integer)]",\
 30, 0, 0.0,0.0,0.0,0,517)
DeclareVariable("clutch3.Backward", "w_relfric < 0 (backward sliding) [:#(type=Integer)]",\
 31, -1, 0.0,0.0,0.0,0,517)
DeclareVariable("clutch3.mode", "Mode of friction (-1: backward sliding, 0: stuck, 1: forward sliding, 2: inactive, 3: unknown) [:#(type=Integer)]",\
 67, 3, -1.0,3.0,0.0,0,660)
DeclareVariable("clutch3.unitAngularAcceleration", "[rad/s2]", 32, 1, 0.0,0.0,\
0.0,0,1537)
DeclareVariable("clutch3.unitTorque", "[N.m]", 33, 1, 0.0,0.0,0.0,0,1537)
DeclareVariable("clutch3.useHeatPort", "= true, if heatPort is enabled [:#(type=Boolean)]",\
 34, false, 0.0,0.0,0.0,0,1539)
DeclareVariable("clutch3.lossPower", "Loss power leaving component via heatPort (> 0, if heat is flowing out of component) [W]",\
 95, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("clutch3.mu", "Friction coefficient", 96, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("clutch3.fn", "Normal force (fn=fn_max*f_normalized) [N]", 68, \
0.0, 0.0,0.0,0.0,0,640)
DeclareVariable("clutch3.f_normalized", "Normalized force signal 0..1 (normal force = fn_max*f_normalized; clutch is engaged if > 0) [1]",\
 69, 0.0, 0.0,0.0,0.0,0,640)
DeclareVariable("clutch3.tableID.id", "[:#(type=Integer)]", 43, 0, 0.0,0.0,0.0,0,2565)
DeclareVariable("clutch3.mu0", "Friction coefficient for w=0 and forward sliding",\
 44, 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("clutch3.table_signs[1]", "Signs for sliding friction coefficient table interpolation: [sign for w_rel, sign for mu] []",\
 97, 0.0, 0.0,0.0,0.0,0,2560)
DeclareVariable("clutch3.table_signs[2]", "Signs for sliding friction coefficient table interpolation: [sign for w_rel, sign for mu] []",\
 98, 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("J4.flange_a.phi", "Absolute rotation angle of flange [rad|deg]", \
"J4.phi", 1, 5, 99, 4)
DeclareAlias2("J4.flange_a.tau", "Cut torque in the flange [N.m]", \
"J3.flange_b.tau", -1, 5, 90, 132)
DeclareAlias2("J4.flange_b.phi", "Absolute rotation angle of flange [rad|deg]", \
"J4.phi", 1, 5, 99, 4)
DeclareVariable("J4.flange_b.tau", "Cut torque in the flange [N.m]", 35, 0.0, \
0.0,0.0,0.0,0,777)
DeclareParameter("J4.J", "Moment of inertia [kg.m2]", 34, 1, 0.0,\
1.7976931348623157E+308,0.0,0,560)
DeclareVariable("J4.stateSelect", "Priority to use phi and w as states [:#(type=StateSelect)]",\
 36, 3, 1.0,5.0,0.0,0,1541)
DeclareVariable("J4.phi", "Absolute rotation angle of component [rad|deg]", 99, 0,\
 0.0,0.0,0.0,0,528)
DeclareAlias2("J4.der(phi)", "der(Absolute rotation angle of component) [rad/s]",\
 "J4.w", 1, 5, 100, 0)
DeclareVariable("J4.w", "Absolute angular velocity of component (= der(phi)) [rad/s]",\
 100, 0, 0.0,0.0,0.0,0,528)
DeclareVariable("J4.der(w)", "der(Absolute angular velocity of component (= der(phi))) [rad/s2]",\
 101, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("J4.a", "Absolute angular acceleration of component (= der(w)) [rad/s2]",\
 "J4.der(w)", 1, 5, 101, 0)
DeclareParameter("sin2.amplitude", "Amplitude of sine wave", 35, 1, 0.0,0.0,0.0,\
0,560)
DeclareVariable("sin2.f", "Frequency of sine wave [Hz]", 45, 1, 0.0,0.0,0.0,0,513)
DeclareParameter("sin2.phase", "Phase of sine wave [rad|deg]", 36, \
1.570796326794897, 0.0,0.0,0.0,0,560)
DeclareVariable("sin2.continuous", "Make output continuous by starting at offset + amplitude*sin(phase) [:#(type=Boolean)]",\
 37, false, 0.0,0.0,0.0,0,515)
DeclareAlias2("sin2.y", "Connector of Real output signal [1]", "clutch1.f_normalized", 1,\
 5, 78, 0)
DeclareParameter("sin2.offset", "Offset of output signal y [1]", 37, 0, 0.0,0.0,\
0.0,0,560)
DeclareParameter("sin2.startTime", "Output y = offset for time < startTime [s]",\
 38, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("step2.height", "Height of step [1]", 39, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("step2.y", "Connector of Real output signal [1]", "clutch3.f_normalized", 1,\
 5, 69, 0)
DeclareParameter("step2.offset", "Offset of output signal y [1]", 40, 0, \
0.0,0.0,0.0,0,560)
DeclareVariable("step2.startTime", "Output y = offset for time < startTime [s]",\
 46, 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("fixed.phi0", "Fixed offset angle of housing [rad|deg]", 41, 0,\
 0.0,0.0,0.0,0,560)
DeclareAlias2("fixed.flange.phi", "Absolute rotation angle of flange [rad|deg]",\
 "fixed.phi0", 1, 7, 41, 4)
DeclareAlias2("fixed.flange.tau", "Cut torque in the flange [N.m]", \
"J1.flange_a.tau", -1, 5, 70, 132)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include "dsblock5.c"
DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartPreBlock
preWD(DYNX(W_,47),"clutch1.free", false, 0);
preD(DYNX(W_,51),"clutch1.mode", 3, 1);
pre(DYNX(W_,49),"clutch1.startBackward", false, 7);
pre(DYNX(W_,48),"clutch1.startForward", false, 6);
preWD(DYNX(W_,55),"clutch2.free", false, 2);
preD(DYNX(W_,59),"clutch2.mode", 3, 3);
pre(DYNX(W_,57),"clutch2.startBackward", false, 9);
pre(DYNX(W_,56),"clutch2.startForward", false, 8);
preWD(DYNX(W_,63),"clutch3.free", false, 4);
preD(DYNX(W_,67),"clutch3.mode", 3, 5);
pre(DYNX(W_,65),"clutch3.startBackward", false, 11);
pre(DYNX(W_,64),"clutch3.startForward", false, 10);
EndPreBlock
StartEqBlock
DoRemember_(DYNX(W_,74), 0.0, 3);
DoRemember_(DYNX(W_,85), 0.0, 2);
DoRemember_(DYNX(W_,94), 0.0, 1);
DoRemember_(DYNX(F_,1), 0.0, 0);
EndEqBlock
EndDataBlock
